/*
 * Autogenerated file, DO NOT EDIT manually!
 *
 * Copyright (c) 2015 Intel Corporation
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 */

#include <linux/sysfs.h>

#include "i915_drv.h"

enum metric_set_id {
	METRIC_SET_ID_RENDER_BASIC = 1,
	METRIC_SET_ID_COMPUTE_BASIC,
	METRIC_SET_ID_RENDER_PIPE_PROFILE,
	METRIC_SET_ID_MEMORY_READS,
	METRIC_SET_ID_MEMORY_WRITES,
	METRIC_SET_ID_COMPUTE_EXTENDED,
	METRIC_SET_ID_COMPUTE_L3_CACHE,
	METRIC_SET_ID_HDC_AND_SF,
	METRIC_SET_ID_L3_1,
	METRIC_SET_ID_RASTERIZER_AND_PIXEL_BACKEND,
	METRIC_SET_ID_SAMPLER,
	METRIC_SET_ID_TDL_1,
	METRIC_SET_ID_TDL_2,
};

int i915_oa_n_builtin_metric_sets_bxt = 13;

static const struct i915_oa_reg b_counter_config_render_basic[] = {
	{ _MMIO(0x2710), 0x00000000 },
	{ _MMIO(0x2714), 0x00800000 },
	{ _MMIO(0x2720), 0x00000000 },
	{ _MMIO(0x2724), 0x00800000 },
};

static const struct i915_oa_reg flex_eu_config_render_basic[] = {
	{ _MMIO(0xE458), 0x00005004 },
	{ _MMIO(0xE558), 0x00010003 },
	{ _MMIO(0xE658), 0x00012011 },
	{ _MMIO(0xE758), 0x00015014 },
	{ _MMIO(0xE45c), 0x00051050 },
	{ _MMIO(0xE55c), 0x00053052 },
	{ _MMIO(0xE65c), 0x00055054 },
};

static const struct i915_oa_reg mux_config_render_basic_0_0_sku_gte_0x03[] = {
	{ _MMIO(0x00009888), 0x166C00F0 },
	{ _MMIO(0x00009888), 0x12120280 },
	{ _MMIO(0x00009888), 0x12320280 },
	{ _MMIO(0x00009888), 0x159303DF },
	{ _MMIO(0x00009888), 0x3F900C00 },
	{ _MMIO(0x00009888), 0x41900000 },
	{ _MMIO(0x00009888), 0x002D1000 },
	{ _MMIO(0x00009888), 0x062D4000 },
	{ _MMIO(0x00009888), 0x082D5000 },
	{ _MMIO(0x00009888), 0x0A2D1000 },
	{ _MMIO(0x00009888), 0x0C2E0800 },
	{ _MMIO(0x00009888), 0x0E2E5900 },
	{ _MMIO(0x00009888), 0x0A4C8000 },
	{ _MMIO(0x00009888), 0x0C4C8000 },
	{ _MMIO(0x00009888), 0x0E4C4000 },
	{ _MMIO(0x00009888), 0x064E8000 },
	{ _MMIO(0x00009888), 0x084E8000 },
	{ _MMIO(0x00009888), 0x0A4E2000 },
	{ _MMIO(0x00009888), 0x1C4F0010 },
	{ _MMIO(0x00009888), 0x0A6C0053 },
	{ _MMIO(0x00009888), 0x106C0000 },
	{ _MMIO(0x00009888), 0x1C6C0000 },
	{ _MMIO(0x00009888), 0x1A0FCC00 },
	{ _MMIO(0x00009888), 0x1C0F0002 },
	{ _MMIO(0x00009888), 0x1C2C0040 },
	{ _MMIO(0x00009888), 0x00101000 },
	{ _MMIO(0x00009888), 0x04101000 },
	{ _MMIO(0x00009888), 0x00114000 },
	{ _MMIO(0x00009888), 0x08114000 },
	{ _MMIO(0x00009888), 0x00120020 },
	{ _MMIO(0x00009888), 0x08120021 },
	{ _MMIO(0x00009888), 0x00141000 },
	{ _MMIO(0x00009888), 0x08141000 },
	{ _MMIO(0x00009888), 0x02308000 },
	{ _MMIO(0x00009888), 0x04302000 },
	{ _MMIO(0x00009888), 0x06318000 },
	{ _MMIO(0x00009888), 0x08318000 },
	{ _MMIO(0x00009888), 0x06320800 },
	{ _MMIO(0x00009888), 0x08320840 },
	{ _MMIO(0x00009888), 0x00320000 },
	{ _MMIO(0x00009888), 0x06344000 },
	{ _MMIO(0x00009888), 0x08344000 },
	{ _MMIO(0x00009888), 0x0D931831 },
	{ _MMIO(0x00009888), 0x0F939F3F },
	{ _MMIO(0x00009888), 0x01939E80 },
	{ _MMIO(0x00009888), 0x03931DBC },
	{ _MMIO(0x00009888), 0x0593003A },
	{ _MMIO(0x00009888), 0x11930000 },
	{ _MMIO(0x00009888), 0x1993002A },
	{ _MMIO(0x00009888), 0x07930000 },
	{ _MMIO(0x00009888), 0x09930000 },
	{ _MMIO(0x00009888), 0x1D900177 },
	{ _MMIO(0x00009888), 0x1F900178 },
	{ _MMIO(0x00009888), 0x35900000 },
	{ _MMIO(0x00009888), 0x13904000 },
	{ _MMIO(0x00009888), 0x21904000 },
	{ _MMIO(0x00009888), 0x23904000 },
	{ _MMIO(0x00009888), 0x25904000 },
	{ _MMIO(0x00009888), 0x27904000 },
	{ _MMIO(0x00009888), 0x2B904000 },
	{ _MMIO(0x00009888), 0x2D904000 },
	{ _MMIO(0x00009888), 0x2F904000 },
	{ _MMIO(0x00009888), 0x31904000 },
	{ _MMIO(0x00009888), 0x15904000 },
	{ _MMIO(0x00009888), 0x17904000 },
	{ _MMIO(0x00009888), 0x19904000 },
	{ _MMIO(0x00009888), 0x1B904000 },
	{ _MMIO(0x00009888), 0x53901110 },
	{ _MMIO(0x00009888), 0x43900423 },
	{ _MMIO(0x00009888), 0x55900111 },
	{ _MMIO(0x00009888), 0x47900C02 },
	{ _MMIO(0x00009888), 0x57900000 },
	{ _MMIO(0x00009888), 0x49900020 },
	{ _MMIO(0x00009888), 0x59901111 },
	{ _MMIO(0x00009888), 0x4B900421 },
	{ _MMIO(0x00009888), 0x37900000 },
	{ _MMIO(0x00009888), 0x33900000 },
	{ _MMIO(0x00009888), 0x4D900001 },
	{ _MMIO(0x00009888), 0x45900821 },
};

static const struct i915_oa_reg mux_config_render_basic_0_0_sku_lt_0x03[] = {
	{ _MMIO(0x00009888), 0x166C00F0 },
	{ _MMIO(0x00009888), 0x12120280 },
	{ _MMIO(0x00009888), 0x12320280 },
	{ _MMIO(0x00009888), 0x159303DF },
	{ _MMIO(0x00009888), 0x3F900C00 },
	{ _MMIO(0x00009888), 0x419000A0 },
	{ _MMIO(0x00009888), 0x002D1000 },
	{ _MMIO(0x00009888), 0x062D4000 },
	{ _MMIO(0x00009888), 0x082D5000 },
	{ _MMIO(0x00009888), 0x0A2D1000 },
	{ _MMIO(0x00009888), 0x0C2E0800 },
	{ _MMIO(0x00009888), 0x0E2E5900 },
	{ _MMIO(0x00009888), 0x0A4C8000 },
	{ _MMIO(0x00009888), 0x0C4C8000 },
	{ _MMIO(0x00009888), 0x0E4C4000 },
	{ _MMIO(0x00009888), 0x064E8000 },
	{ _MMIO(0x00009888), 0x084E8000 },
	{ _MMIO(0x00009888), 0x0A4E2000 },
	{ _MMIO(0x00009888), 0x1C4F0010 },
	{ _MMIO(0x00009888), 0x0A6C0053 },
	{ _MMIO(0x00009888), 0x106C0000 },
	{ _MMIO(0x00009888), 0x1C6C0000 },
	{ _MMIO(0x00009888), 0x1A0FCC00 },
	{ _MMIO(0x00009888), 0x1C0F0002 },
	{ _MMIO(0x00009888), 0x1C2C0040 },
	{ _MMIO(0x00009888), 0x00101000 },
	{ _MMIO(0x00009888), 0x04101000 },
	{ _MMIO(0x00009888), 0x00114000 },
	{ _MMIO(0x00009888), 0x08114000 },
	{ _MMIO(0x00009888), 0x00120020 },
	{ _MMIO(0x00009888), 0x08120021 },
	{ _MMIO(0x00009888), 0x00141000 },
	{ _MMIO(0x00009888), 0x08141000 },
	{ _MMIO(0x00009888), 0x02308000 },
	{ _MMIO(0x00009888), 0x04302000 },
	{ _MMIO(0x00009888), 0x06318000 },
	{ _MMIO(0x00009888), 0x08318000 },
	{ _MMIO(0x00009888), 0x06320800 },
	{ _MMIO(0x00009888), 0x08320840 },
	{ _MMIO(0x00009888), 0x00320000 },
	{ _MMIO(0x00009888), 0x06344000 },
	{ _MMIO(0x00009888), 0x08344000 },
	{ _MMIO(0x00009888), 0x0D931831 },
	{ _MMIO(0x00009888), 0x0F939F3F },
	{ _MMIO(0x00009888), 0x01939E80 },
	{ _MMIO(0x00009888), 0x03931DBC },
	{ _MMIO(0x00009888), 0x0593003A },
	{ _MMIO(0x00009888), 0x11930000 },
	{ _MMIO(0x00009888), 0x1993002A },
	{ _MMIO(0x00009888), 0x07930000 },
	{ _MMIO(0x00009888), 0x09930000 },
	{ _MMIO(0x00009888), 0x1D900177 },
	{ _MMIO(0x00009888), 0x1F900187 },
	{ _MMIO(0x00009888), 0x35900000 },
	{ _MMIO(0x00009888), 0x13904000 },
	{ _MMIO(0x00009888), 0x21904000 },
	{ _MMIO(0x00009888), 0x23904000 },
	{ _MMIO(0x00009888), 0x25904000 },
	{ _MMIO(0x00009888), 0x27904000 },
	{ _MMIO(0x00009888), 0x2B904000 },
	{ _MMIO(0x00009888), 0x2D904000 },
	{ _MMIO(0x00009888), 0x2F904000 },
	{ _MMIO(0x00009888), 0x31904000 },
	{ _MMIO(0x00009888), 0x15904000 },
	{ _MMIO(0x00009888), 0x17904000 },
	{ _MMIO(0x00009888), 0x19904000 },
	{ _MMIO(0x00009888), 0x1B904000 },
	{ _MMIO(0x00009888), 0x53901110 },
	{ _MMIO(0x00009888), 0x43900423 },
	{ _MMIO(0x00009888), 0x55900111 },
	{ _MMIO(0x00009888), 0x47900C02 },
	{ _MMIO(0x00009888), 0x57900000 },
	{ _MMIO(0x00009888), 0x49900020 },
	{ _MMIO(0x00009888), 0x59901111 },
	{ _MMIO(0x00009888), 0x4B900421 },
	{ _MMIO(0x00009888), 0x37900000 },
	{ _MMIO(0x00009888), 0x33900000 },
	{ _MMIO(0x00009888), 0x4D900001 },
	{ _MMIO(0x00009888), 0x45900821 },
};

static int select_render_basic_config(struct drm_i915_private *dev_priv)
{
	if (dev_priv->dev->pdev->revision >= 0x03) {
		dev_priv->perf.oa.mux_regs =
			mux_config_render_basic_0_0_sku_gte_0x03;
		dev_priv->perf.oa.mux_regs_len =
			ARRAY_SIZE(mux_config_render_basic_0_0_sku_gte_0x03);
	} else if (dev_priv->dev->pdev->revision < 0x03) {
		dev_priv->perf.oa.mux_regs =
			mux_config_render_basic_0_0_sku_lt_0x03;
		dev_priv->perf.oa.mux_regs_len =
			ARRAY_SIZE(mux_config_render_basic_0_0_sku_lt_0x03);
	} else {
		DRM_DEBUG_DRIVER("No suitable MUX config for \"RENDER_BASIC\" metric set");
		return -EINVAL;
	}

	dev_priv->perf.oa.b_counter_regs =
		b_counter_config_render_basic;
	dev_priv->perf.oa.b_counter_regs_len =
		ARRAY_SIZE(b_counter_config_render_basic);

	dev_priv->perf.oa.flex_regs =
		flex_eu_config_render_basic;
	dev_priv->perf.oa.flex_regs_len =
		ARRAY_SIZE(flex_eu_config_render_basic);

	return 0;
}

static const struct i915_oa_reg b_counter_config_compute_basic[] = {
	{ _MMIO(0x2710), 0x00000000 },
	{ _MMIO(0x2714), 0x00800000 },
	{ _MMIO(0x2720), 0x00000000 },
	{ _MMIO(0x2724), 0x00800000 },
};

static const struct i915_oa_reg flex_eu_config_compute_basic[] = {
	{ _MMIO(0xE458), 0x00005004 },
	{ _MMIO(0xE558), 0x00000003 },
	{ _MMIO(0xE658), 0x00002001 },
	{ _MMIO(0xE758), 0x00778008 },
	{ _MMIO(0xE45c), 0x00088078 },
	{ _MMIO(0xE55c), 0x00808708 },
	{ _MMIO(0xE65c), 0x00a08908 },
};

static const struct i915_oa_reg mux_config_compute_basic[] = {
	{ _MMIO(0x00009888), 0x104F00E0 },
	{ _MMIO(0x00009888), 0x124F1C00 },
	{ _MMIO(0x00009888), 0x39900340 },
	{ _MMIO(0x00009888), 0x3F900C00 },
	{ _MMIO(0x00009888), 0x41900000 },
	{ _MMIO(0x00009888), 0x002D5000 },
	{ _MMIO(0x00009888), 0x062D4000 },
	{ _MMIO(0x00009888), 0x082D4000 },
	{ _MMIO(0x00009888), 0x0A2D1000 },
	{ _MMIO(0x00009888), 0x0C2D5000 },
	{ _MMIO(0x00009888), 0x0E2D4000 },
	{ _MMIO(0x00009888), 0x0C2E1400 },
	{ _MMIO(0x00009888), 0x0E2E5100 },
	{ _MMIO(0x00009888), 0x102E0114 },
	{ _MMIO(0x00009888), 0x044CC000 },
	{ _MMIO(0x00009888), 0x0A4C8000 },
	{ _MMIO(0x00009888), 0x0C4C8000 },
	{ _MMIO(0x00009888), 0x0E4C4000 },
	{ _MMIO(0x00009888), 0x104C8000 },
	{ _MMIO(0x00009888), 0x124C8000 },
	{ _MMIO(0x00009888), 0x164C2000 },
	{ _MMIO(0x00009888), 0x004EA000 },
	{ _MMIO(0x00009888), 0x064E8000 },
	{ _MMIO(0x00009888), 0x084E8000 },
	{ _MMIO(0x00009888), 0x0A4E2000 },
	{ _MMIO(0x00009888), 0x0C4EA000 },
	{ _MMIO(0x00009888), 0x0E4E8000 },
	{ _MMIO(0x00009888), 0x004F6B42 },
	{ _MMIO(0x00009888), 0x064F6200 },
	{ _MMIO(0x00009888), 0x084F4100 },
	{ _MMIO(0x00009888), 0x0A4F0061 },
	{ _MMIO(0x00009888), 0x0C4F6C4C },
	{ _MMIO(0x00009888), 0x0E4F4B00 },
	{ _MMIO(0x00009888), 0x1A4F0000 },
	{ _MMIO(0x00009888), 0x1C4F0000 },
	{ _MMIO(0x00009888), 0x180F5000 },
	{ _MMIO(0x00009888), 0x1A0F8800 },
	{ _MMIO(0x00009888), 0x1C0F08A2 },
	{ _MMIO(0x00009888), 0x182C4000 },
	{ _MMIO(0x00009888), 0x1C2C1451 },
	{ _MMIO(0x00009888), 0x1E2C0001 },
	{ _MMIO(0x00009888), 0x1A2C0010 },
	{ _MMIO(0x00009888), 0x01938000 },
	{ _MMIO(0x00009888), 0x0F938000 },
	{ _MMIO(0x00009888), 0x19938A28 },
	{ _MMIO(0x00009888), 0x03938000 },
	{ _MMIO(0x00009888), 0x19900177 },
	{ _MMIO(0x00009888), 0x1B900178 },
	{ _MMIO(0x00009888), 0x1D900125 },
	{ _MMIO(0x00009888), 0x1F900123 },
	{ _MMIO(0x00009888), 0x35900000 },
	{ _MMIO(0x00009888), 0x13904000 },
	{ _MMIO(0x00009888), 0x21904000 },
	{ _MMIO(0x00009888), 0x25904000 },
	{ _MMIO(0x00009888), 0x27904000 },
	{ _MMIO(0x00009888), 0x2B904000 },
	{ _MMIO(0x00009888), 0x2D904000 },
	{ _MMIO(0x00009888), 0x31904000 },
	{ _MMIO(0x00009888), 0x15904000 },
	{ _MMIO(0x00009888), 0x53901000 },
	{ _MMIO(0x00009888), 0x43900000 },
	{ _MMIO(0x00009888), 0x55900111 },
	{ _MMIO(0x00009888), 0x47900000 },
	{ _MMIO(0x00009888), 0x57900000 },
	{ _MMIO(0x00009888), 0x49900000 },
	{ _MMIO(0x00009888), 0x59900000 },
	{ _MMIO(0x00009888), 0x4B900000 },
	{ _MMIO(0x00009888), 0x37900000 },
	{ _MMIO(0x00009888), 0x33900000 },
	{ _MMIO(0x00009888), 0x4D900000 },
	{ _MMIO(0x00009888), 0x45900000 },
};

static int select_compute_basic_config(struct drm_i915_private *dev_priv)
{
	dev_priv->perf.oa.mux_regs =
		mux_config_compute_basic;
	dev_priv->perf.oa.mux_regs_len =
		ARRAY_SIZE(mux_config_compute_basic);

	dev_priv->perf.oa.b_counter_regs =
		b_counter_config_compute_basic;
	dev_priv->perf.oa.b_counter_regs_len =
		ARRAY_SIZE(b_counter_config_compute_basic);

	dev_priv->perf.oa.flex_regs =
		flex_eu_config_compute_basic;
	dev_priv->perf.oa.flex_regs_len =
		ARRAY_SIZE(flex_eu_config_compute_basic);

	return 0;
}

static const struct i915_oa_reg b_counter_config_render_pipe_profile[] = {
	{ _MMIO(0x2724), 0xf0800000 },
	{ _MMIO(0x2720), 0x00000000 },
	{ _MMIO(0x2714), 0xf0800000 },
	{ _MMIO(0x2710), 0x00000000 },
	{ _MMIO(0x2770), 0x0007ffea },
	{ _MMIO(0x2774), 0x00007ffc },
	{ _MMIO(0x2778), 0x0007affa },
	{ _MMIO(0x277c), 0x0000f5fd },
	{ _MMIO(0x2780), 0x00079ffa },
	{ _MMIO(0x2784), 0x0000f3fb },
	{ _MMIO(0x2788), 0x0007bf7a },
	{ _MMIO(0x278c), 0x0000f7e7 },
	{ _MMIO(0x2790), 0x0007fefa },
	{ _MMIO(0x2794), 0x0000f7cf },
	{ _MMIO(0x2798), 0x00077ffa },
	{ _MMIO(0x279c), 0x0000efdf },
	{ _MMIO(0x27a0), 0x0006fffa },
	{ _MMIO(0x27a4), 0x0000cfbf },
	{ _MMIO(0x27a8), 0x0003fffa },
	{ _MMIO(0x27ac), 0x00005f7f },
};

static const struct i915_oa_reg flex_eu_config_render_pipe_profile[] = {
	{ _MMIO(0xE458), 0x00005004 },
	{ _MMIO(0xE558), 0x00015014 },
	{ _MMIO(0xE658), 0x00025024 },
	{ _MMIO(0xE758), 0x00035034 },
	{ _MMIO(0xE45c), 0x00045044 },
	{ _MMIO(0xE55c), 0x00055054 },
	{ _MMIO(0xE65c), 0x00065064 },
};

static const struct i915_oa_reg mux_config_render_pipe_profile[] = {
	{ _MMIO(0x00009888), 0x0C2E001F },
	{ _MMIO(0x00009888), 0x0A2F0000 },
	{ _MMIO(0x00009888), 0x10186800 },
	{ _MMIO(0x00009888), 0x11810019 },
	{ _MMIO(0x00009888), 0x15810013 },
	{ _MMIO(0x00009888), 0x13820020 },
	{ _MMIO(0x00009888), 0x11830020 },
	{ _MMIO(0x00009888), 0x17840000 },
	{ _MMIO(0x00009888), 0x11860007 },
	{ _MMIO(0x00009888), 0x21860000 },
	{ _MMIO(0x00009888), 0x178703E0 },
	{ _MMIO(0x00009888), 0x0C2D8000 },
	{ _MMIO(0x00009888), 0x042D4000 },
	{ _MMIO(0x00009888), 0x062D1000 },
	{ _MMIO(0x00009888), 0x022E5400 },
	{ _MMIO(0x00009888), 0x002E0000 },
	{ _MMIO(0x00009888), 0x0E2E0080 },
	{ _MMIO(0x00009888), 0x082F0040 },
	{ _MMIO(0x00009888), 0x002F0000 },
	{ _MMIO(0x00009888), 0x06143000 },
	{ _MMIO(0x00009888), 0x06174000 },
	{ _MMIO(0x00009888), 0x06180012 },
	{ _MMIO(0x00009888), 0x00180000 },
	{ _MMIO(0x00009888), 0x0D804000 },
	{ _MMIO(0x00009888), 0x0F804000 },
	{ _MMIO(0x00009888), 0x05804000 },
	{ _MMIO(0x00009888), 0x09810200 },
	{ _MMIO(0x00009888), 0x0B810030 },
	{ _MMIO(0x00009888), 0x03810003 },
	{ _MMIO(0x00009888), 0x21819140 },
	{ _MMIO(0x00009888), 0x23819050 },
	{ _MMIO(0x00009888), 0x25810018 },
	{ _MMIO(0x00009888), 0x0B820980 },
	{ _MMIO(0x00009888), 0x03820D80 },
	{ _MMIO(0x00009888), 0x11820000 },
	{ _MMIO(0x00009888), 0x0182C000 },
	{ _MMIO(0x00009888), 0x07828000 },
	{ _MMIO(0x00009888), 0x09824000 },
	{ _MMIO(0x00009888), 0x0F828000 },
	{ _MMIO(0x00009888), 0x0D830004 },
	{ _MMIO(0x00009888), 0x0583000C },
	{ _MMIO(0x00009888), 0x0F831000 },
	{ _MMIO(0x00009888), 0x01848072 },
	{ _MMIO(0x00009888), 0x11840000 },
	{ _MMIO(0x00009888), 0x07848000 },
	{ _MMIO(0x00009888), 0x09844000 },
	{ _MMIO(0x00009888), 0x0F848000 },
	{ _MMIO(0x00009888), 0x07860000 },
	{ _MMIO(0x00009888), 0x09860092 },
	{ _MMIO(0x00009888), 0x0F860400 },
	{ _MMIO(0x00009888), 0x01869100 },
	{ _MMIO(0x00009888), 0x0F870065 },
	{ _MMIO(0x00009888), 0x01870000 },
	{ _MMIO(0x00009888), 0x19930800 },
	{ _MMIO(0x00009888), 0x0B938000 },
	{ _MMIO(0x00009888), 0x0D938000 },
	{ _MMIO(0x00009888), 0x1B952000 },
	{ _MMIO(0x00009888), 0x1D955055 },
	{ _MMIO(0x00009888), 0x1F951455 },
	{ _MMIO(0x00009888), 0x0992A000 },
	{ _MMIO(0x00009888), 0x0F928000 },
	{ _MMIO(0x00009888), 0x1192A800 },
	{ _MMIO(0x00009888), 0x1392028A },
	{ _MMIO(0x00009888), 0x0B92A000 },
	{ _MMIO(0x00009888), 0x0D922000 },
	{ _MMIO(0x00009888), 0x13908000 },
	{ _MMIO(0x00009888), 0x21908000 },
	{ _MMIO(0x00009888), 0x23908000 },
	{ _MMIO(0x00009888), 0x25908000 },
	{ _MMIO(0x00009888), 0x27908000 },
	{ _MMIO(0x00009888), 0x29908000 },
	{ _MMIO(0x00009888), 0x2B908000 },
	{ _MMIO(0x00009888), 0x2D904000 },
	{ _MMIO(0x00009888), 0x2F908000 },
	{ _MMIO(0x00009888), 0x31908000 },
	{ _MMIO(0x00009888), 0x15908000 },
	{ _MMIO(0x00009888), 0x17908000 },
	{ _MMIO(0x00009888), 0x19908000 },
	{ _MMIO(0x00009888), 0x1B908000 },
	{ _MMIO(0x00009888), 0x1D904000 },
	{ _MMIO(0x00009888), 0x1F904000 },
	{ _MMIO(0x00009888), 0x53900000 },
	{ _MMIO(0x00009888), 0x43900C01 },
	{ _MMIO(0x00009888), 0x55900000 },
	{ _MMIO(0x00009888), 0x47900000 },
	{ _MMIO(0x00009888), 0x57900000 },
	{ _MMIO(0x00009888), 0x49900863 },
	{ _MMIO(0x00009888), 0x59900000 },
	{ _MMIO(0x00009888), 0x4B900061 },
	{ _MMIO(0x00009888), 0x37900000 },
	{ _MMIO(0x00009888), 0x33900000 },
	{ _MMIO(0x00009888), 0x4D900000 },
	{ _MMIO(0x00009888), 0x45900C22 },
};

static int select_render_pipe_profile_config(struct drm_i915_private *dev_priv)
{
	dev_priv->perf.oa.mux_regs =
		mux_config_render_pipe_profile;
	dev_priv->perf.oa.mux_regs_len =
		ARRAY_SIZE(mux_config_render_pipe_profile);

	dev_priv->perf.oa.b_counter_regs =
		b_counter_config_render_pipe_profile;
	dev_priv->perf.oa.b_counter_regs_len =
		ARRAY_SIZE(b_counter_config_render_pipe_profile);

	dev_priv->perf.oa.flex_regs =
		flex_eu_config_render_pipe_profile;
	dev_priv->perf.oa.flex_regs_len =
		ARRAY_SIZE(flex_eu_config_render_pipe_profile);

	return 0;
}

static const struct i915_oa_reg b_counter_config_memory_reads[] = {
	{ _MMIO(0x272c), 0xffffffff },
	{ _MMIO(0x2728), 0xffffffff },
	{ _MMIO(0x2724), 0xf0800000 },
	{ _MMIO(0x2720), 0x00000000 },
	{ _MMIO(0x271c), 0xffffffff },
	{ _MMIO(0x2718), 0xffffffff },
	{ _MMIO(0x2714), 0xf0800000 },
	{ _MMIO(0x2710), 0x00000000 },
	{ _MMIO(0x274c), 0x86543210 },
	{ _MMIO(0x2748), 0x86543210 },
	{ _MMIO(0x2744), 0x00006667 },
	{ _MMIO(0x2740), 0x00000000 },
	{ _MMIO(0x275c), 0x86543210 },
	{ _MMIO(0x2758), 0x86543210 },
	{ _MMIO(0x2754), 0x00006465 },
	{ _MMIO(0x2750), 0x00000000 },
	{ _MMIO(0x2770), 0x0007f81a },
	{ _MMIO(0x2774), 0x0000fe00 },
	{ _MMIO(0x2778), 0x0007f82a },
	{ _MMIO(0x277c), 0x0000fe00 },
	{ _MMIO(0x2780), 0x0007f872 },
	{ _MMIO(0x2784), 0x0000fe00 },
	{ _MMIO(0x2788), 0x0007f8ba },
	{ _MMIO(0x278c), 0x0000fe00 },
	{ _MMIO(0x2790), 0x0007f87a },
	{ _MMIO(0x2794), 0x0000fe00 },
	{ _MMIO(0x2798), 0x0007f8ea },
	{ _MMIO(0x279c), 0x0000fe00 },
	{ _MMIO(0x27a0), 0x0007f8e2 },
	{ _MMIO(0x27a4), 0x0000fe00 },
	{ _MMIO(0x27a8), 0x0007f8f2 },
	{ _MMIO(0x27ac), 0x0000fe00 },
};

static const struct i915_oa_reg flex_eu_config_memory_reads[] = {
	{ _MMIO(0xE458), 0x00005004 },
	{ _MMIO(0xE558), 0x00015014 },
	{ _MMIO(0xE658), 0x00025024 },
	{ _MMIO(0xE758), 0x00035034 },
	{ _MMIO(0xE45c), 0x00045044 },
	{ _MMIO(0xE55c), 0x00055054 },
	{ _MMIO(0xE65c), 0x00065064 },
};

static const struct i915_oa_reg mux_config_memory_reads[] = {
	{ _MMIO(0x00009888), 0x19800343 },
	{ _MMIO(0x00009888), 0x39900340 },
	{ _MMIO(0x00009888), 0x3F901000 },
	{ _MMIO(0x00009888), 0x41900003 },
	{ _MMIO(0x00009888), 0x03803180 },
	{ _MMIO(0x00009888), 0x058035E2 },
	{ _MMIO(0x00009888), 0x0780006A },
	{ _MMIO(0x00009888), 0x11800000 },
	{ _MMIO(0x00009888), 0x2181A000 },
	{ _MMIO(0x00009888), 0x2381000A },
	{ _MMIO(0x00009888), 0x1D950550 },
	{ _MMIO(0x00009888), 0x0B928000 },
	{ _MMIO(0x00009888), 0x0D92A000 },
	{ _MMIO(0x00009888), 0x0F922000 },
	{ _MMIO(0x00009888), 0x13900170 },
	{ _MMIO(0x00009888), 0x21900171 },
	{ _MMIO(0x00009888), 0x23900172 },
	{ _MMIO(0x00009888), 0x25900173 },
	{ _MMIO(0x00009888), 0x27900174 },
	{ _MMIO(0x00009888), 0x29900175 },
	{ _MMIO(0x00009888), 0x2B900176 },
	{ _MMIO(0x00009888), 0x2D900177 },
	{ _MMIO(0x00009888), 0x2F90017F },
	{ _MMIO(0x00009888), 0x31900125 },
	{ _MMIO(0x00009888), 0x15900123 },
	{ _MMIO(0x00009888), 0x17900121 },
	{ _MMIO(0x00009888), 0x35900000 },
	{ _MMIO(0x00009888), 0x19908000 },
	{ _MMIO(0x00009888), 0x1B908000 },
	{ _MMIO(0x00009888), 0x1D908000 },
	{ _MMIO(0x00009888), 0x1F908000 },
	{ _MMIO(0x00009888), 0x53900000 },
	{ _MMIO(0x00009888), 0x43901084 },
	{ _MMIO(0x00009888), 0x55900000 },
	{ _MMIO(0x00009888), 0x47901080 },
	{ _MMIO(0x00009888), 0x57900000 },
	{ _MMIO(0x00009888), 0x49901084 },
	{ _MMIO(0x00009888), 0x59900000 },
	{ _MMIO(0x00009888), 0x4B901084 },
	{ _MMIO(0x00009888), 0x37900000 },
	{ _MMIO(0x00009888), 0x33900000 },
	{ _MMIO(0x00009888), 0x4D900004 },
	{ _MMIO(0x00009888), 0x45900000 },
};

static int select_memory_reads_config(struct drm_i915_private *dev_priv)
{
	dev_priv->perf.oa.mux_regs =
		mux_config_memory_reads;
	dev_priv->perf.oa.mux_regs_len =
		ARRAY_SIZE(mux_config_memory_reads);

	dev_priv->perf.oa.b_counter_regs =
		b_counter_config_memory_reads;
	dev_priv->perf.oa.b_counter_regs_len =
		ARRAY_SIZE(b_counter_config_memory_reads);

	dev_priv->perf.oa.flex_regs =
		flex_eu_config_memory_reads;
	dev_priv->perf.oa.flex_regs_len =
		ARRAY_SIZE(flex_eu_config_memory_reads);

	return 0;
}

static const struct i915_oa_reg b_counter_config_memory_writes[] = {
	{ _MMIO(0x272c), 0xffffffff },
	{ _MMIO(0x2728), 0xffffffff },
	{ _MMIO(0x2724), 0xf0800000 },
	{ _MMIO(0x2720), 0x00000000 },
	{ _MMIO(0x271c), 0xffffffff },
	{ _MMIO(0x2718), 0xffffffff },
	{ _MMIO(0x2714), 0xf0800000 },
	{ _MMIO(0x2710), 0x00000000 },
	{ _MMIO(0x274c), 0x86543210 },
	{ _MMIO(0x2748), 0x86543210 },
	{ _MMIO(0x2744), 0x00006667 },
	{ _MMIO(0x2740), 0x00000000 },
	{ _MMIO(0x275c), 0x86543210 },
	{ _MMIO(0x2758), 0x86543210 },
	{ _MMIO(0x2754), 0x00006465 },
	{ _MMIO(0x2750), 0x00000000 },
	{ _MMIO(0x2770), 0x0007f81a },
	{ _MMIO(0x2774), 0x0000fe00 },
	{ _MMIO(0x2778), 0x0007f82a },
	{ _MMIO(0x277c), 0x0000fe00 },
	{ _MMIO(0x2780), 0x0007f822 },
	{ _MMIO(0x2784), 0x0000fe00 },
	{ _MMIO(0x2788), 0x0007f8ba },
	{ _MMIO(0x278c), 0x0000fe00 },
	{ _MMIO(0x2790), 0x0007f87a },
	{ _MMIO(0x2794), 0x0000fe00 },
	{ _MMIO(0x2798), 0x0007f8ea },
	{ _MMIO(0x279c), 0x0000fe00 },
	{ _MMIO(0x27a0), 0x0007f8e2 },
	{ _MMIO(0x27a4), 0x0000fe00 },
	{ _MMIO(0x27a8), 0x0007f8f2 },
	{ _MMIO(0x27ac), 0x0000fe00 },
};

static const struct i915_oa_reg flex_eu_config_memory_writes[] = {
	{ _MMIO(0xE458), 0x00005004 },
	{ _MMIO(0xE558), 0x00015014 },
	{ _MMIO(0xE658), 0x00025024 },
	{ _MMIO(0xE758), 0x00035034 },
	{ _MMIO(0xE45c), 0x00045044 },
	{ _MMIO(0xE55c), 0x00055054 },
	{ _MMIO(0xE65c), 0x00065064 },
};

static const struct i915_oa_reg mux_config_memory_writes[] = {
	{ _MMIO(0x00009888), 0x19800343 },
	{ _MMIO(0x00009888), 0x39900340 },
	{ _MMIO(0x00009888), 0x3F900000 },
	{ _MMIO(0x00009888), 0x41900080 },
	{ _MMIO(0x00009888), 0x03803180 },
	{ _MMIO(0x00009888), 0x058035E2 },
	{ _MMIO(0x00009888), 0x0780006A },
	{ _MMIO(0x00009888), 0x11800000 },
	{ _MMIO(0x00009888), 0x2181A000 },
	{ _MMIO(0x00009888), 0x2381000A },
	{ _MMIO(0x00009888), 0x1D950550 },
	{ _MMIO(0x00009888), 0x0B928000 },
	{ _MMIO(0x00009888), 0x0D92A000 },
	{ _MMIO(0x00009888), 0x0F922000 },
	{ _MMIO(0x00009888), 0x13900180 },
	{ _MMIO(0x00009888), 0x21900181 },
	{ _MMIO(0x00009888), 0x23900182 },
	{ _MMIO(0x00009888), 0x25900183 },
	{ _MMIO(0x00009888), 0x27900184 },
	{ _MMIO(0x00009888), 0x29900185 },
	{ _MMIO(0x00009888), 0x2B900186 },
	{ _MMIO(0x00009888), 0x2D900187 },
	{ _MMIO(0x00009888), 0x2F900170 },
	{ _MMIO(0x00009888), 0x31900125 },
	{ _MMIO(0x00009888), 0x15900123 },
	{ _MMIO(0x00009888), 0x17900121 },
	{ _MMIO(0x00009888), 0x35900000 },
	{ _MMIO(0x00009888), 0x19908000 },
	{ _MMIO(0x00009888), 0x1B908000 },
	{ _MMIO(0x00009888), 0x1D908000 },
	{ _MMIO(0x00009888), 0x1F908000 },
	{ _MMIO(0x00009888), 0x53900000 },
	{ _MMIO(0x00009888), 0x43901084 },
	{ _MMIO(0x00009888), 0x55900000 },
	{ _MMIO(0x00009888), 0x47901080 },
	{ _MMIO(0x00009888), 0x57900000 },
	{ _MMIO(0x00009888), 0x49901084 },
	{ _MMIO(0x00009888), 0x59900000 },
	{ _MMIO(0x00009888), 0x4B901084 },
	{ _MMIO(0x00009888), 0x37900000 },
	{ _MMIO(0x00009888), 0x33900000 },
	{ _MMIO(0x00009888), 0x4D900004 },
	{ _MMIO(0x00009888), 0x45900000 },
};

static int select_memory_writes_config(struct drm_i915_private *dev_priv)
{
	dev_priv->perf.oa.mux_regs =
		mux_config_memory_writes;
	dev_priv->perf.oa.mux_regs_len =
		ARRAY_SIZE(mux_config_memory_writes);

	dev_priv->perf.oa.b_counter_regs =
		b_counter_config_memory_writes;
	dev_priv->perf.oa.b_counter_regs_len =
		ARRAY_SIZE(b_counter_config_memory_writes);

	dev_priv->perf.oa.flex_regs =
		flex_eu_config_memory_writes;
	dev_priv->perf.oa.flex_regs_len =
		ARRAY_SIZE(flex_eu_config_memory_writes);

	return 0;
}

static const struct i915_oa_reg b_counter_config_compute_extended[] = {
	{ _MMIO(0x2724), 0xf0800000 },
	{ _MMIO(0x2720), 0x00000000 },
	{ _MMIO(0x2714), 0xf0800000 },
	{ _MMIO(0x2710), 0x00000000 },
	{ _MMIO(0x2770), 0x0007fc2a },
	{ _MMIO(0x2774), 0x0000bf00 },
	{ _MMIO(0x2778), 0x0007fc6a },
	{ _MMIO(0x277c), 0x0000bf00 },
	{ _MMIO(0x2780), 0x0007fc92 },
	{ _MMIO(0x2784), 0x0000bf00 },
	{ _MMIO(0x2788), 0x0007fca2 },
	{ _MMIO(0x278c), 0x0000bf00 },
	{ _MMIO(0x2790), 0x0007fc32 },
	{ _MMIO(0x2794), 0x0000bf00 },
	{ _MMIO(0x2798), 0x0007fc9a },
	{ _MMIO(0x279c), 0x0000bf00 },
	{ _MMIO(0x27a0), 0x0007fe6a },
	{ _MMIO(0x27a4), 0x0000bf00 },
	{ _MMIO(0x27a8), 0x0007fe7a },
	{ _MMIO(0x27ac), 0x0000bf00 },
};

static const struct i915_oa_reg flex_eu_config_compute_extended[] = {
	{ _MMIO(0xE458), 0x00005004 },
	{ _MMIO(0xE558), 0x00000003 },
	{ _MMIO(0xE658), 0x00002001 },
	{ _MMIO(0xE758), 0x00778008 },
	{ _MMIO(0xE45c), 0x00088078 },
	{ _MMIO(0xE55c), 0x00808708 },
	{ _MMIO(0xE65c), 0x00a08908 },
};

static const struct i915_oa_reg mux_config_compute_extended[] = {
	{ _MMIO(0x00009888), 0x104F00E0 },
	{ _MMIO(0x00009888), 0x141C0160 },
	{ _MMIO(0x00009888), 0x161C0015 },
	{ _MMIO(0x00009888), 0x181C0120 },
	{ _MMIO(0x00009888), 0x002D5000 },
	{ _MMIO(0x00009888), 0x062D4000 },
	{ _MMIO(0x00009888), 0x082D5000 },
	{ _MMIO(0x00009888), 0x0A2D5000 },
	{ _MMIO(0x00009888), 0x0C2D5000 },
	{ _MMIO(0x00009888), 0x0E2D5000 },
	{ _MMIO(0x00009888), 0x022D5000 },
	{ _MMIO(0x00009888), 0x042D5000 },
	{ _MMIO(0x00009888), 0x0C2E5400 },
	{ _MMIO(0x00009888), 0x0E2E5515 },
	{ _MMIO(0x00009888), 0x102E0155 },
	{ _MMIO(0x00009888), 0x044CC000 },
	{ _MMIO(0x00009888), 0x0A4C8000 },
	{ _MMIO(0x00009888), 0x0C4CC000 },
	{ _MMIO(0x00009888), 0x0E4CC000 },
	{ _MMIO(0x00009888), 0x104C8000 },
	{ _MMIO(0x00009888), 0x124C8000 },
	{ _MMIO(0x00009888), 0x144C8000 },
	{ _MMIO(0x00009888), 0x164C2000 },
	{ _MMIO(0x00009888), 0x064CC000 },
	{ _MMIO(0x00009888), 0x084CC000 },
	{ _MMIO(0x00009888), 0x004EA000 },
	{ _MMIO(0x00009888), 0x064E8000 },
	{ _MMIO(0x00009888), 0x084EA000 },
	{ _MMIO(0x00009888), 0x0A4EA000 },
	{ _MMIO(0x00009888), 0x0C4EA000 },
	{ _MMIO(0x00009888), 0x0E4EA000 },
	{ _MMIO(0x00009888), 0x024EA000 },
	{ _MMIO(0x00009888), 0x044EA000 },
	{ _MMIO(0x00009888), 0x0E4F4B41 },
	{ _MMIO(0x00009888), 0x004F4200 },
	{ _MMIO(0x00009888), 0x024F404C },
	{ _MMIO(0x00009888), 0x1C4F0000 },
	{ _MMIO(0x00009888), 0x1A4F0000 },
	{ _MMIO(0x00009888), 0x001B4000 },
	{ _MMIO(0x00009888), 0x061B8000 },
	{ _MMIO(0x00009888), 0x081BC000 },
	{ _MMIO(0x00009888), 0x0A1BC000 },
	{ _MMIO(0x00009888), 0x0C1BC000 },
	{ _MMIO(0x00009888), 0x041BC000 },
	{ _MMIO(0x00009888), 0x001C0031 },
	{ _MMIO(0x00009888), 0x061C1900 },
	{ _MMIO(0x00009888), 0x081C1A33 },
	{ _MMIO(0x00009888), 0x0A1C1B35 },
	{ _MMIO(0x00009888), 0x0C1C3337 },
	{ _MMIO(0x00009888), 0x041C31C7 },
	{ _MMIO(0x00009888), 0x180F5000 },
	{ _MMIO(0x00009888), 0x1A0FA8AA },
	{ _MMIO(0x00009888), 0x1C0F0AAA },
	{ _MMIO(0x00009888), 0x182C8000 },
	{ _MMIO(0x00009888), 0x1C2C6AAA },
	{ _MMIO(0x00009888), 0x1E2C0001 },
	{ _MMIO(0x00009888), 0x1A2C2950 },
	{ _MMIO(0x00009888), 0x01938000 },
	{ _MMIO(0x00009888), 0x0F938000 },
	{ _MMIO(0x00009888), 0x1993AAAA },
	{ _MMIO(0x00009888), 0x03938000 },
	{ _MMIO(0x00009888), 0x05938000 },
	{ _MMIO(0x00009888), 0x07938000 },
	{ _MMIO(0x00009888), 0x09938000 },
	{ _MMIO(0x00009888), 0x0B938000 },
	{ _MMIO(0x00009888), 0x13904000 },
	{ _MMIO(0x00009888), 0x21904000 },
	{ _MMIO(0x00009888), 0x23904000 },
	{ _MMIO(0x00009888), 0x25904000 },
	{ _MMIO(0x00009888), 0x27904000 },
	{ _MMIO(0x00009888), 0x29904000 },
	{ _MMIO(0x00009888), 0x2B904000 },
	{ _MMIO(0x00009888), 0x2D904000 },
	{ _MMIO(0x00009888), 0x2F904000 },
	{ _MMIO(0x00009888), 0x31904000 },
	{ _MMIO(0x00009888), 0x15904000 },
	{ _MMIO(0x00009888), 0x17904000 },
	{ _MMIO(0x00009888), 0x19904000 },
	{ _MMIO(0x00009888), 0x1B904000 },
	{ _MMIO(0x00009888), 0x1D904000 },
	{ _MMIO(0x00009888), 0x53900000 },
	{ _MMIO(0x00009888), 0x43900420 },
	{ _MMIO(0x00009888), 0x55900000 },
	{ _MMIO(0x00009888), 0x47900000 },
	{ _MMIO(0x00009888), 0x57900000 },
	{ _MMIO(0x00009888), 0x49900000 },
	{ _MMIO(0x00009888), 0x59900000 },
	{ _MMIO(0x00009888), 0x4B900400 },
	{ _MMIO(0x00009888), 0x37900000 },
	{ _MMIO(0x00009888), 0x33900000 },
	{ _MMIO(0x00009888), 0x4D900001 },
	{ _MMIO(0x00009888), 0x45900001 },
};

static int select_compute_extended_config(struct drm_i915_private *dev_priv)
{
	dev_priv->perf.oa.mux_regs =
		mux_config_compute_extended;
	dev_priv->perf.oa.mux_regs_len =
		ARRAY_SIZE(mux_config_compute_extended);

	dev_priv->perf.oa.b_counter_regs =
		b_counter_config_compute_extended;
	dev_priv->perf.oa.b_counter_regs_len =
		ARRAY_SIZE(b_counter_config_compute_extended);

	dev_priv->perf.oa.flex_regs =
		flex_eu_config_compute_extended;
	dev_priv->perf.oa.flex_regs_len =
		ARRAY_SIZE(flex_eu_config_compute_extended);

	return 0;
}

static const struct i915_oa_reg b_counter_config_compute_l3_cache[] = {
	{ _MMIO(0x2710), 0x00000000 },
	{ _MMIO(0x2714), 0x30800000 },
	{ _MMIO(0x2720), 0x00000000 },
	{ _MMIO(0x2724), 0x30800000 },
	{ _MMIO(0x2770), 0x0007fffa },
	{ _MMIO(0x2774), 0x0000fefe },
	{ _MMIO(0x2778), 0x0007fffa },
	{ _MMIO(0x277c), 0x0000fefd },
	{ _MMIO(0x2790), 0x0007fffa },
	{ _MMIO(0x2794), 0x0000fbef },
	{ _MMIO(0x2798), 0x0007fffa },
	{ _MMIO(0x279c), 0x0000fbdf },
};

static const struct i915_oa_reg flex_eu_config_compute_l3_cache[] = {
	{ _MMIO(0xE458), 0x00005004 },
	{ _MMIO(0xE558), 0x00000003 },
	{ _MMIO(0xE658), 0x00002001 },
	{ _MMIO(0xE758), 0x00101100 },
	{ _MMIO(0xE45c), 0x00201200 },
	{ _MMIO(0xE55c), 0x00301300 },
	{ _MMIO(0xE65c), 0x00401400 },
};

static const struct i915_oa_reg mux_config_compute_l3_cache[] = {
	{ _MMIO(0x00009888), 0x166C03B0 },
	{ _MMIO(0x00009888), 0x1593001E },
	{ _MMIO(0x00009888), 0x3F900C00 },
	{ _MMIO(0x00009888), 0x41900000 },
	{ _MMIO(0x00009888), 0x002D1000 },
	{ _MMIO(0x00009888), 0x062D4000 },
	{ _MMIO(0x00009888), 0x082D5000 },
	{ _MMIO(0x00009888), 0x0E2D5000 },
	{ _MMIO(0x00009888), 0x0C2E0400 },
	{ _MMIO(0x00009888), 0x0E2E1500 },
	{ _MMIO(0x00009888), 0x102E0140 },
	{ _MMIO(0x00009888), 0x044C4000 },
	{ _MMIO(0x00009888), 0x0A4C8000 },
	{ _MMIO(0x00009888), 0x0C4CC000 },
	{ _MMIO(0x00009888), 0x144C8000 },
	{ _MMIO(0x00009888), 0x164C2000 },
	{ _MMIO(0x00009888), 0x004E2000 },
	{ _MMIO(0x00009888), 0x064E8000 },
	{ _MMIO(0x00009888), 0x084EA000 },
	{ _MMIO(0x00009888), 0x0E4EA000 },
	{ _MMIO(0x00009888), 0x1A4F4001 },
	{ _MMIO(0x00009888), 0x1C4F5005 },
	{ _MMIO(0x00009888), 0x006C0051 },
	{ _MMIO(0x00009888), 0x066C5000 },
	{ _MMIO(0x00009888), 0x086C5C5D },
	{ _MMIO(0x00009888), 0x0E6C5E5F },
	{ _MMIO(0x00009888), 0x106C0000 },
	{ _MMIO(0x00009888), 0x146C0000 },
	{ _MMIO(0x00009888), 0x1A6C0000 },
	{ _MMIO(0x00009888), 0x1C6C0000 },
	{ _MMIO(0x00009888), 0x180F1000 },
	{ _MMIO(0x00009888), 0x1A0FA800 },
	{ _MMIO(0x00009888), 0x1C0F0A00 },
	{ _MMIO(0x00009888), 0x182C4000 },
	{ _MMIO(0x00009888), 0x1C2C4015 },
	{ _MMIO(0x00009888), 0x1E2C0001 },
	{ _MMIO(0x00009888), 0x03931980 },
	{ _MMIO(0x00009888), 0x05930032 },
	{ _MMIO(0x00009888), 0x11930000 },
	{ _MMIO(0x00009888), 0x01938000 },
	{ _MMIO(0x00009888), 0x0F938000 },
	{ _MMIO(0x00009888), 0x1993A00A },
	{ _MMIO(0x00009888), 0x07930000 },
	{ _MMIO(0x00009888), 0x09930000 },
	{ _MMIO(0x00009888), 0x1D900177 },
	{ _MMIO(0x00009888), 0x1F900178 },
	{ _MMIO(0x00009888), 0x35900000 },
	{ _MMIO(0x00009888), 0x13904000 },
	{ _MMIO(0x00009888), 0x21904000 },
	{ _MMIO(0x00009888), 0x23904000 },
	{ _MMIO(0x00009888), 0x25904000 },
	{ _MMIO(0x00009888), 0x2F904000 },
	{ _MMIO(0x00009888), 0x31904000 },
	{ _MMIO(0x00009888), 0x19904000 },
	{ _MMIO(0x00009888), 0x1B904000 },
	{ _MMIO(0x00009888), 0x53901000 },
	{ _MMIO(0x00009888), 0x43900000 },
	{ _MMIO(0x00009888), 0x55900111 },
	{ _MMIO(0x00009888), 0x47900001 },
	{ _MMIO(0x00009888), 0x57900000 },
	{ _MMIO(0x00009888), 0x49900000 },
	{ _MMIO(0x00009888), 0x37900000 },
	{ _MMIO(0x00009888), 0x33900000 },
	{ _MMIO(0x00009888), 0x59900000 },
	{ _MMIO(0x00009888), 0x4B900000 },
	{ _MMIO(0x00009888), 0x4D900000 },
	{ _MMIO(0x00009888), 0x45900400 },
};

static int select_compute_l3_cache_config(struct drm_i915_private *dev_priv)
{
	dev_priv->perf.oa.mux_regs =
		mux_config_compute_l3_cache;
	dev_priv->perf.oa.mux_regs_len =
		ARRAY_SIZE(mux_config_compute_l3_cache);

	dev_priv->perf.oa.b_counter_regs =
		b_counter_config_compute_l3_cache;
	dev_priv->perf.oa.b_counter_regs_len =
		ARRAY_SIZE(b_counter_config_compute_l3_cache);

	dev_priv->perf.oa.flex_regs =
		flex_eu_config_compute_l3_cache;
	dev_priv->perf.oa.flex_regs_len =
		ARRAY_SIZE(flex_eu_config_compute_l3_cache);

	return 0;
}

static const struct i915_oa_reg b_counter_config_hdc_and_sf[] = {
	{ _MMIO(0x2740), 0x00000000 },
	{ _MMIO(0x2744), 0x00800000 },
	{ _MMIO(0x2710), 0x00000000 },
	{ _MMIO(0x2714), 0x10800000 },
	{ _MMIO(0x2720), 0x00000000 },
	{ _MMIO(0x2724), 0x00800000 },
	{ _MMIO(0x2770), 0x00000002 },
	{ _MMIO(0x2774), 0x0000fdff },
};

static const struct i915_oa_reg flex_eu_config_hdc_and_sf[] = {
	{ _MMIO(0xE458), 0x00005004 },
	{ _MMIO(0xE558), 0x00010003 },
	{ _MMIO(0xE658), 0x00012011 },
	{ _MMIO(0xE758), 0x00015014 },
	{ _MMIO(0xE45c), 0x00051050 },
	{ _MMIO(0xE55c), 0x00053052 },
	{ _MMIO(0xE65c), 0x00055054 },
};

static const struct i915_oa_reg mux_config_hdc_and_sf[] = {
	{ _MMIO(0x00009888), 0x104F0232 },
	{ _MMIO(0x00009888), 0x124F4640 },
	{ _MMIO(0x00009888), 0x11834400 },
	{ _MMIO(0x00009888), 0x022D4000 },
	{ _MMIO(0x00009888), 0x042D5000 },
	{ _MMIO(0x00009888), 0x062D1000 },
	{ _MMIO(0x00009888), 0x0E2E0055 },
	{ _MMIO(0x00009888), 0x064C8000 },
	{ _MMIO(0x00009888), 0x084CC000 },
	{ _MMIO(0x00009888), 0x0A4C4000 },
	{ _MMIO(0x00009888), 0x024E8000 },
	{ _MMIO(0x00009888), 0x044EA000 },
	{ _MMIO(0x00009888), 0x064E2000 },
	{ _MMIO(0x00009888), 0x024F6100 },
	{ _MMIO(0x00009888), 0x044F416B },
	{ _MMIO(0x00009888), 0x064F004B },
	{ _MMIO(0x00009888), 0x1A4F0000 },
	{ _MMIO(0x00009888), 0x1A0F02A8 },
	{ _MMIO(0x00009888), 0x1A2C5500 },
	{ _MMIO(0x00009888), 0x0F808000 },
	{ _MMIO(0x00009888), 0x25810020 },
	{ _MMIO(0x00009888), 0x0F8305C0 },
	{ _MMIO(0x00009888), 0x07938000 },
	{ _MMIO(0x00009888), 0x09938000 },
	{ _MMIO(0x00009888), 0x0B938000 },
	{ _MMIO(0x00009888), 0x0D938000 },
	{ _MMIO(0x00009888), 0x1F951000 },
	{ _MMIO(0x00009888), 0x13920200 },
	{ _MMIO(0x00009888), 0x31908000 },
	{ _MMIO(0x00009888), 0x19904000 },
	{ _MMIO(0x00009888), 0x1B904000 },
	{ _MMIO(0x00009888), 0x1D904000 },
	{ _MMIO(0x00009888), 0x1F904000 },
	{ _MMIO(0x00009888), 0x37900000 },
	{ _MMIO(0x00009888), 0x59900000 },
	{ _MMIO(0x00009888), 0x4D900003 },
	{ _MMIO(0x00009888), 0x53900000 },
	{ _MMIO(0x00009888), 0x45900000 },
	{ _MMIO(0x00009888), 0x55900000 },
	{ _MMIO(0x00009888), 0x47900000 },
	{ _MMIO(0x00009888), 0x33900000 },
};

static int select_hdc_and_sf_config(struct drm_i915_private *dev_priv)
{
	dev_priv->perf.oa.mux_regs =
		mux_config_hdc_and_sf;
	dev_priv->perf.oa.mux_regs_len =
		ARRAY_SIZE(mux_config_hdc_and_sf);

	dev_priv->perf.oa.b_counter_regs =
		b_counter_config_hdc_and_sf;
	dev_priv->perf.oa.b_counter_regs_len =
		ARRAY_SIZE(b_counter_config_hdc_and_sf);

	dev_priv->perf.oa.flex_regs =
		flex_eu_config_hdc_and_sf;
	dev_priv->perf.oa.flex_regs_len =
		ARRAY_SIZE(flex_eu_config_hdc_and_sf);

	return 0;
}

static const struct i915_oa_reg b_counter_config_l3_1[] = {
	{ _MMIO(0x2740), 0x00000000 },
	{ _MMIO(0x2744), 0x00800000 },
	{ _MMIO(0x2710), 0x00000000 },
	{ _MMIO(0x2714), 0xf0800000 },
	{ _MMIO(0x2720), 0x00000000 },
	{ _MMIO(0x2724), 0xf0800000 },
	{ _MMIO(0x2770), 0x00100070 },
	{ _MMIO(0x2774), 0x0000fff1 },
	{ _MMIO(0x2778), 0x00014002 },
	{ _MMIO(0x277c), 0x0000c3ff },
	{ _MMIO(0x2780), 0x00010002 },
	{ _MMIO(0x2784), 0x0000c7ff },
	{ _MMIO(0x2788), 0x00004002 },
	{ _MMIO(0x278c), 0x0000d3ff },
	{ _MMIO(0x2790), 0x00100700 },
	{ _MMIO(0x2794), 0x0000ff1f },
	{ _MMIO(0x2798), 0x00001402 },
	{ _MMIO(0x279c), 0x0000fc3f },
	{ _MMIO(0x27a0), 0x00001002 },
	{ _MMIO(0x27a4), 0x0000fc7f },
	{ _MMIO(0x27a8), 0x00000402 },
	{ _MMIO(0x27ac), 0x0000fd3f },
};

static const struct i915_oa_reg flex_eu_config_l3_1[] = {
	{ _MMIO(0xE458), 0x00005004 },
	{ _MMIO(0xE558), 0x00010003 },
	{ _MMIO(0xE658), 0x00012011 },
	{ _MMIO(0xE758), 0x00015014 },
	{ _MMIO(0xE45c), 0x00051050 },
	{ _MMIO(0xE55c), 0x00053052 },
	{ _MMIO(0xE65c), 0x00055054 },
};

static const struct i915_oa_reg mux_config_l3_1_0_0_sku_gte_0x03[] = {
	{ _MMIO(0x00009888), 0x12643400 },
	{ _MMIO(0x00009888), 0x12653400 },
	{ _MMIO(0x00009888), 0x106C6800 },
	{ _MMIO(0x00009888), 0x126C001E },
	{ _MMIO(0x00009888), 0x166C0010 },
	{ _MMIO(0x00009888), 0x0C2D5000 },
	{ _MMIO(0x00009888), 0x0E2D5000 },
	{ _MMIO(0x00009888), 0x002D4000 },
	{ _MMIO(0x00009888), 0x022D5000 },
	{ _MMIO(0x00009888), 0x042D5000 },
	{ _MMIO(0x00009888), 0x062D1000 },
	{ _MMIO(0x00009888), 0x102E0154 },
	{ _MMIO(0x00009888), 0x0C2E5000 },
	{ _MMIO(0x00009888), 0x0E2E0055 },
	{ _MMIO(0x00009888), 0x104C8000 },
	{ _MMIO(0x00009888), 0x124C8000 },
	{ _MMIO(0x00009888), 0x144C8000 },
	{ _MMIO(0x00009888), 0x164C2000 },
	{ _MMIO(0x00009888), 0x044C8000 },
	{ _MMIO(0x00009888), 0x064CC000 },
	{ _MMIO(0x00009888), 0x084CC000 },
	{ _MMIO(0x00009888), 0x0A4C4000 },
	{ _MMIO(0x00009888), 0x0C4EA000 },
	{ _MMIO(0x00009888), 0x0E4EA000 },
	{ _MMIO(0x00009888), 0x004E8000 },
	{ _MMIO(0x00009888), 0x024EA000 },
	{ _MMIO(0x00009888), 0x044EA000 },
	{ _MMIO(0x00009888), 0x064E2000 },
	{ _MMIO(0x00009888), 0x1C4F5500 },
	{ _MMIO(0x00009888), 0x1A4F1554 },
	{ _MMIO(0x00009888), 0x0A640024 },
	{ _MMIO(0x00009888), 0x10640000 },
	{ _MMIO(0x00009888), 0x04640000 },
	{ _MMIO(0x00009888), 0x0C650024 },
	{ _MMIO(0x00009888), 0x10650000 },
	{ _MMIO(0x00009888), 0x06650000 },
	{ _MMIO(0x00009888), 0x0C6C5327 },
	{ _MMIO(0x00009888), 0x0E6C5425 },
	{ _MMIO(0x00009888), 0x006C2A00 },
	{ _MMIO(0x00009888), 0x026C285B },
	{ _MMIO(0x00009888), 0x046C005C },
	{ _MMIO(0x00009888), 0x1C6C0000 },
	{ _MMIO(0x00009888), 0x1A6C0900 },
	{ _MMIO(0x00009888), 0x1C0F0AA0 },
	{ _MMIO(0x00009888), 0x180F4000 },
	{ _MMIO(0x00009888), 0x1A0F02AA },
	{ _MMIO(0x00009888), 0x1C2C5400 },
	{ _MMIO(0x00009888), 0x1E2C0001 },
	{ _MMIO(0x00009888), 0x1A2C5550 },
	{ _MMIO(0x00009888), 0x1993AA00 },
	{ _MMIO(0x00009888), 0x03938000 },
	{ _MMIO(0x00009888), 0x05938000 },
	{ _MMIO(0x00009888), 0x07938000 },
	{ _MMIO(0x00009888), 0x09938000 },
	{ _MMIO(0x00009888), 0x0B938000 },
	{ _MMIO(0x00009888), 0x0D938000 },
	{ _MMIO(0x00009888), 0x2B904000 },
	{ _MMIO(0x00009888), 0x2D904000 },
	{ _MMIO(0x00009888), 0x2F904000 },
	{ _MMIO(0x00009888), 0x31904000 },
	{ _MMIO(0x00009888), 0x15904000 },
	{ _MMIO(0x00009888), 0x17904000 },
	{ _MMIO(0x00009888), 0x19904000 },
	{ _MMIO(0x00009888), 0x1B904000 },
	{ _MMIO(0x00009888), 0x1D904000 },
	{ _MMIO(0x00009888), 0x1F904000 },
	{ _MMIO(0x00009888), 0x59900000 },
	{ _MMIO(0x00009888), 0x4B900421 },
	{ _MMIO(0x00009888), 0x37900000 },
	{ _MMIO(0x00009888), 0x33900000 },
	{ _MMIO(0x00009888), 0x4D900001 },
	{ _MMIO(0x00009888), 0x53900000 },
	{ _MMIO(0x00009888), 0x43900420 },
	{ _MMIO(0x00009888), 0x45900021 },
	{ _MMIO(0x00009888), 0x55900000 },
	{ _MMIO(0x00009888), 0x47900000 },
};

static const struct i915_oa_reg mux_config_l3_1_0_0_sku_lt_0x03[] = {
	{ _MMIO(0x00009888), 0x14640340 },
	{ _MMIO(0x00009888), 0x14650340 },
	{ _MMIO(0x00009888), 0x106C6800 },
	{ _MMIO(0x00009888), 0x126C001E },
	{ _MMIO(0x00009888), 0x166C0010 },
	{ _MMIO(0x00009888), 0x0C2D5000 },
	{ _MMIO(0x00009888), 0x0E2D5000 },
	{ _MMIO(0x00009888), 0x002D4000 },
	{ _MMIO(0x00009888), 0x022D5000 },
	{ _MMIO(0x00009888), 0x042D5000 },
	{ _MMIO(0x00009888), 0x062D1000 },
	{ _MMIO(0x00009888), 0x102E0154 },
	{ _MMIO(0x00009888), 0x0C2E5000 },
	{ _MMIO(0x00009888), 0x0E2E0055 },
	{ _MMIO(0x00009888), 0x104C8000 },
	{ _MMIO(0x00009888), 0x124C8000 },
	{ _MMIO(0x00009888), 0x144C8000 },
	{ _MMIO(0x00009888), 0x164C2000 },
	{ _MMIO(0x00009888), 0x044C8000 },
	{ _MMIO(0x00009888), 0x064CC000 },
	{ _MMIO(0x00009888), 0x084CC000 },
	{ _MMIO(0x00009888), 0x0A4C4000 },
	{ _MMIO(0x00009888), 0x0C4EA000 },
	{ _MMIO(0x00009888), 0x0E4EA000 },
	{ _MMIO(0x00009888), 0x004E8000 },
	{ _MMIO(0x00009888), 0x024EA000 },
	{ _MMIO(0x00009888), 0x044EA000 },
	{ _MMIO(0x00009888), 0x064E2000 },
	{ _MMIO(0x00009888), 0x1C4F5500 },
	{ _MMIO(0x00009888), 0x1A4F1554 },
	{ _MMIO(0x00009888), 0x04642400 },
	{ _MMIO(0x00009888), 0x22640000 },
	{ _MMIO(0x00009888), 0x1A640000 },
	{ _MMIO(0x00009888), 0x06650024 },
	{ _MMIO(0x00009888), 0x22650000 },
	{ _MMIO(0x00009888), 0x1C650000 },
	{ _MMIO(0x00009888), 0x0C6C5327 },
	{ _MMIO(0x00009888), 0x0E6C5425 },
	{ _MMIO(0x00009888), 0x006C2A00 },
	{ _MMIO(0x00009888), 0x026C285B },
	{ _MMIO(0x00009888), 0x046C005C },
	{ _MMIO(0x00009888), 0x1C6C0000 },
	{ _MMIO(0x00009888), 0x1A6C0900 },
	{ _MMIO(0x00009888), 0x1C0F0AA0 },
	{ _MMIO(0x00009888), 0x180F4000 },
	{ _MMIO(0x00009888), 0x1A0F02AA },
	{ _MMIO(0x00009888), 0x1C2C5400 },
	{ _MMIO(0x00009888), 0x1E2C0001 },
	{ _MMIO(0x00009888), 0x1A2C5550 },
	{ _MMIO(0x00009888), 0x1993AA00 },
	{ _MMIO(0x00009888), 0x03938000 },
	{ _MMIO(0x00009888), 0x05938000 },
	{ _MMIO(0x00009888), 0x07938000 },
	{ _MMIO(0x00009888), 0x09938000 },
	{ _MMIO(0x00009888), 0x0B938000 },
	{ _MMIO(0x00009888), 0x0D938000 },
	{ _MMIO(0x00009888), 0x2B904000 },
	{ _MMIO(0x00009888), 0x2D904000 },
	{ _MMIO(0x00009888), 0x2F904000 },
	{ _MMIO(0x00009888), 0x31904000 },
	{ _MMIO(0x00009888), 0x15904000 },
	{ _MMIO(0x00009888), 0x17904000 },
	{ _MMIO(0x00009888), 0x19904000 },
	{ _MMIO(0x00009888), 0x1B904000 },
	{ _MMIO(0x00009888), 0x1D904000 },
	{ _MMIO(0x00009888), 0x1F904000 },
	{ _MMIO(0x00009888), 0x59900000 },
	{ _MMIO(0x00009888), 0x4B900421 },
	{ _MMIO(0x00009888), 0x37900000 },
	{ _MMIO(0x00009888), 0x33900000 },
	{ _MMIO(0x00009888), 0x4D900001 },
	{ _MMIO(0x00009888), 0x53900000 },
	{ _MMIO(0x00009888), 0x43900420 },
	{ _MMIO(0x00009888), 0x45900021 },
	{ _MMIO(0x00009888), 0x55900000 },
	{ _MMIO(0x00009888), 0x47900000 },
};

static int select_l3_1_config(struct drm_i915_private *dev_priv)
{
	if (dev_priv->dev->pdev->revision >= 0x03) {
		dev_priv->perf.oa.mux_regs =
			mux_config_l3_1_0_0_sku_gte_0x03;
		dev_priv->perf.oa.mux_regs_len =
			ARRAY_SIZE(mux_config_l3_1_0_0_sku_gte_0x03);
	} else if (dev_priv->dev->pdev->revision < 0x03) {
		dev_priv->perf.oa.mux_regs =
			mux_config_l3_1_0_0_sku_lt_0x03;
		dev_priv->perf.oa.mux_regs_len =
			ARRAY_SIZE(mux_config_l3_1_0_0_sku_lt_0x03);
	} else {
		DRM_DEBUG_DRIVER("No suitable MUX config for \"L3_1\" metric set");
		return -EINVAL;
	}

	dev_priv->perf.oa.b_counter_regs =
		b_counter_config_l3_1;
	dev_priv->perf.oa.b_counter_regs_len =
		ARRAY_SIZE(b_counter_config_l3_1);

	dev_priv->perf.oa.flex_regs =
		flex_eu_config_l3_1;
	dev_priv->perf.oa.flex_regs_len =
		ARRAY_SIZE(flex_eu_config_l3_1);

	return 0;
}

static const struct i915_oa_reg b_counter_config_rasterizer_and_pixel_backend[] = {
	{ _MMIO(0x2740), 0x00000000 },
	{ _MMIO(0x2744), 0x00800000 },
	{ _MMIO(0x2710), 0x00000000 },
	{ _MMIO(0x2714), 0x30800000 },
	{ _MMIO(0x2720), 0x00000000 },
	{ _MMIO(0x2724), 0x00800000 },
	{ _MMIO(0x2770), 0x00000002 },
	{ _MMIO(0x2774), 0x0000efff },
	{ _MMIO(0x2778), 0x00006000 },
	{ _MMIO(0x277c), 0x0000f3ff },
};

static const struct i915_oa_reg flex_eu_config_rasterizer_and_pixel_backend[] = {
	{ _MMIO(0xE458), 0x00005004 },
	{ _MMIO(0xE558), 0x00010003 },
	{ _MMIO(0xE658), 0x00012011 },
	{ _MMIO(0xE758), 0x00015014 },
	{ _MMIO(0xE45c), 0x00051050 },
	{ _MMIO(0xE55c), 0x00053052 },
	{ _MMIO(0xE65c), 0x00055054 },
};

static const struct i915_oa_reg mux_config_rasterizer_and_pixel_backend[] = {
	{ _MMIO(0x00009888), 0x102D7800 },
	{ _MMIO(0x00009888), 0x122D79E0 },
	{ _MMIO(0x00009888), 0x0C2F0004 },
	{ _MMIO(0x00009888), 0x100E3800 },
	{ _MMIO(0x00009888), 0x180F0005 },
	{ _MMIO(0x00009888), 0x002D0940 },
	{ _MMIO(0x00009888), 0x022D802F },
	{ _MMIO(0x00009888), 0x042D4013 },
	{ _MMIO(0x00009888), 0x062D1000 },
	{ _MMIO(0x00009888), 0x0E2E0050 },
	{ _MMIO(0x00009888), 0x022F0010 },
	{ _MMIO(0x00009888), 0x002F0000 },
	{ _MMIO(0x00009888), 0x084C8000 },
	{ _MMIO(0x00009888), 0x0A4C4000 },
	{ _MMIO(0x00009888), 0x044E8000 },
	{ _MMIO(0x00009888), 0x064E2000 },
	{ _MMIO(0x00009888), 0x040E0480 },
	{ _MMIO(0x00009888), 0x000E0000 },
	{ _MMIO(0x00009888), 0x060F0027 },
	{ _MMIO(0x00009888), 0x100F0000 },
	{ _MMIO(0x00009888), 0x1A0F0040 },
	{ _MMIO(0x00009888), 0x03938000 },
	{ _MMIO(0x00009888), 0x05938000 },
	{ _MMIO(0x00009888), 0x07938000 },
	{ _MMIO(0x00009888), 0x09938000 },
	{ _MMIO(0x00009888), 0x0B938000 },
	{ _MMIO(0x00009888), 0x0D938000 },
	{ _MMIO(0x00009888), 0x15904000 },
	{ _MMIO(0x00009888), 0x17904000 },
	{ _MMIO(0x00009888), 0x19904000 },
	{ _MMIO(0x00009888), 0x1B904000 },
	{ _MMIO(0x00009888), 0x1D904000 },
	{ _MMIO(0x00009888), 0x1F904000 },
	{ _MMIO(0x00009888), 0x37900000 },
	{ _MMIO(0x00009888), 0x53900000 },
	{ _MMIO(0x00009888), 0x439014A0 },
	{ _MMIO(0x00009888), 0x459000A4 },
	{ _MMIO(0x00009888), 0x55900000 },
	{ _MMIO(0x00009888), 0x47900001 },
	{ _MMIO(0x00009888), 0x33900000 },
};

static int select_rasterizer_and_pixel_backend_config(struct drm_i915_private *dev_priv)
{
	dev_priv->perf.oa.mux_regs =
		mux_config_rasterizer_and_pixel_backend;
	dev_priv->perf.oa.mux_regs_len =
		ARRAY_SIZE(mux_config_rasterizer_and_pixel_backend);

	dev_priv->perf.oa.b_counter_regs =
		b_counter_config_rasterizer_and_pixel_backend;
	dev_priv->perf.oa.b_counter_regs_len =
		ARRAY_SIZE(b_counter_config_rasterizer_and_pixel_backend);

	dev_priv->perf.oa.flex_regs =
		flex_eu_config_rasterizer_and_pixel_backend;
	dev_priv->perf.oa.flex_regs_len =
		ARRAY_SIZE(flex_eu_config_rasterizer_and_pixel_backend);

	return 0;
}

static const struct i915_oa_reg b_counter_config_sampler[] = {
	{ _MMIO(0x2740), 0x00000000 },
	{ _MMIO(0x2744), 0x00800000 },
	{ _MMIO(0x2710), 0x00000000 },
	{ _MMIO(0x2714), 0x70800000 },
	{ _MMIO(0x2720), 0x00000000 },
	{ _MMIO(0x2724), 0x00800000 },
	{ _MMIO(0x2770), 0x0000c000 },
	{ _MMIO(0x2774), 0x0000e7ff },
	{ _MMIO(0x2778), 0x00003000 },
	{ _MMIO(0x277c), 0x0000f9ff },
	{ _MMIO(0x2780), 0x00000c00 },
	{ _MMIO(0x2784), 0x0000fe7f },
};

static const struct i915_oa_reg flex_eu_config_sampler[] = {
	{ _MMIO(0xE458), 0x00005004 },
	{ _MMIO(0xE558), 0x00010003 },
	{ _MMIO(0xE658), 0x00012011 },
	{ _MMIO(0xE758), 0x00015014 },
	{ _MMIO(0xE45c), 0x00051050 },
	{ _MMIO(0xE55c), 0x00053052 },
	{ _MMIO(0xE65c), 0x00055054 },
};

static const struct i915_oa_reg mux_config_sampler[] = {
	{ _MMIO(0x00009888), 0x121300A0 },
	{ _MMIO(0x00009888), 0x141600AB },
	{ _MMIO(0x00009888), 0x123300A0 },
	{ _MMIO(0x00009888), 0x143600AB },
	{ _MMIO(0x00009888), 0x125300A0 },
	{ _MMIO(0x00009888), 0x145600AB },
	{ _MMIO(0x00009888), 0x0C2D4000 },
	{ _MMIO(0x00009888), 0x0E2D5000 },
	{ _MMIO(0x00009888), 0x002D4000 },
	{ _MMIO(0x00009888), 0x022D5000 },
	{ _MMIO(0x00009888), 0x042D5000 },
	{ _MMIO(0x00009888), 0x062D1000 },
	{ _MMIO(0x00009888), 0x102E01A0 },
	{ _MMIO(0x00009888), 0x0C2E5000 },
	{ _MMIO(0x00009888), 0x0E2E0065 },
	{ _MMIO(0x00009888), 0x164C2000 },
	{ _MMIO(0x00009888), 0x044C8000 },
	{ _MMIO(0x00009888), 0x064CC000 },
	{ _MMIO(0x00009888), 0x084C4000 },
	{ _MMIO(0x00009888), 0x0A4C4000 },
	{ _MMIO(0x00009888), 0x0E4E8000 },
	{ _MMIO(0x00009888), 0x004E8000 },
	{ _MMIO(0x00009888), 0x024EA000 },
	{ _MMIO(0x00009888), 0x044E2000 },
	{ _MMIO(0x00009888), 0x064E2000 },
	{ _MMIO(0x00009888), 0x1C0F0800 },
	{ _MMIO(0x00009888), 0x180F4000 },
	{ _MMIO(0x00009888), 0x1A0F023F },
	{ _MMIO(0x00009888), 0x1E2C0003 },
	{ _MMIO(0x00009888), 0x1A2CC030 },
	{ _MMIO(0x00009888), 0x04132180 },
	{ _MMIO(0x00009888), 0x02130000 },
	{ _MMIO(0x00009888), 0x0C148000 },
	{ _MMIO(0x00009888), 0x0E142000 },
	{ _MMIO(0x00009888), 0x04148000 },
	{ _MMIO(0x00009888), 0x1E150140 },
	{ _MMIO(0x00009888), 0x1C150040 },
	{ _MMIO(0x00009888), 0x0C163000 },
	{ _MMIO(0x00009888), 0x0E160068 },
	{ _MMIO(0x00009888), 0x10160000 },
	{ _MMIO(0x00009888), 0x18160000 },
	{ _MMIO(0x00009888), 0x0A164000 },
	{ _MMIO(0x00009888), 0x04330043 },
	{ _MMIO(0x00009888), 0x02330000 },
	{ _MMIO(0x00009888), 0x0234A000 },
	{ _MMIO(0x00009888), 0x04342000 },
	{ _MMIO(0x00009888), 0x1C350015 },
	{ _MMIO(0x00009888), 0x02363460 },
	{ _MMIO(0x00009888), 0x10360000 },
	{ _MMIO(0x00009888), 0x04360000 },
	{ _MMIO(0x00009888), 0x06360000 },
	{ _MMIO(0x00009888), 0x08364000 },
	{ _MMIO(0x00009888), 0x06530043 },
	{ _MMIO(0x00009888), 0x02530000 },
	{ _MMIO(0x00009888), 0x0E548000 },
	{ _MMIO(0x00009888), 0x00548000 },
	{ _MMIO(0x00009888), 0x06542000 },
	{ _MMIO(0x00009888), 0x1E550400 },
	{ _MMIO(0x00009888), 0x1A552000 },
	{ _MMIO(0x00009888), 0x1C550100 },
	{ _MMIO(0x00009888), 0x0E563000 },
	{ _MMIO(0x00009888), 0x00563400 },
	{ _MMIO(0x00009888), 0x10560000 },
	{ _MMIO(0x00009888), 0x18560000 },
	{ _MMIO(0x00009888), 0x02560000 },
	{ _MMIO(0x00009888), 0x0C564000 },
	{ _MMIO(0x00009888), 0x1993A800 },
	{ _MMIO(0x00009888), 0x03938000 },
	{ _MMIO(0x00009888), 0x05938000 },
	{ _MMIO(0x00009888), 0x07938000 },
	{ _MMIO(0x00009888), 0x09938000 },
	{ _MMIO(0x00009888), 0x0B938000 },
	{ _MMIO(0x00009888), 0x0D938000 },
	{ _MMIO(0x00009888), 0x2D904000 },
	{ _MMIO(0x00009888), 0x2F904000 },
	{ _MMIO(0x00009888), 0x31904000 },
	{ _MMIO(0x00009888), 0x15904000 },
	{ _MMIO(0x00009888), 0x17904000 },
	{ _MMIO(0x00009888), 0x19904000 },
	{ _MMIO(0x00009888), 0x1B904000 },
	{ _MMIO(0x00009888), 0x1D904000 },
	{ _MMIO(0x00009888), 0x1F904000 },
	{ _MMIO(0x00009888), 0x59900000 },
	{ _MMIO(0x00009888), 0x4B9014A0 },
	{ _MMIO(0x00009888), 0x37900000 },
	{ _MMIO(0x00009888), 0x33900000 },
	{ _MMIO(0x00009888), 0x4D900001 },
	{ _MMIO(0x00009888), 0x53900000 },
	{ _MMIO(0x00009888), 0x43900820 },
	{ _MMIO(0x00009888), 0x45901022 },
	{ _MMIO(0x00009888), 0x55900000 },
	{ _MMIO(0x00009888), 0x47900000 },
};

static int select_sampler_config(struct drm_i915_private *dev_priv)
{
	dev_priv->perf.oa.mux_regs =
		mux_config_sampler;
	dev_priv->perf.oa.mux_regs_len =
		ARRAY_SIZE(mux_config_sampler);

	dev_priv->perf.oa.b_counter_regs =
		b_counter_config_sampler;
	dev_priv->perf.oa.b_counter_regs_len =
		ARRAY_SIZE(b_counter_config_sampler);

	dev_priv->perf.oa.flex_regs =
		flex_eu_config_sampler;
	dev_priv->perf.oa.flex_regs_len =
		ARRAY_SIZE(flex_eu_config_sampler);

	return 0;
}

static const struct i915_oa_reg b_counter_config_tdl_1[] = {
	{ _MMIO(0x2740), 0x00000000 },
	{ _MMIO(0x2744), 0x00800000 },
	{ _MMIO(0x2710), 0x00000000 },
	{ _MMIO(0x2714), 0xf0800000 },
	{ _MMIO(0x2720), 0x00000000 },
	{ _MMIO(0x2724), 0x30800000 },
	{ _MMIO(0x2770), 0x00000002 },
	{ _MMIO(0x2774), 0x00007fff },
	{ _MMIO(0x2778), 0x00000000 },
	{ _MMIO(0x277c), 0x00009fff },
	{ _MMIO(0x2780), 0x00000002 },
	{ _MMIO(0x2784), 0x0000efff },
	{ _MMIO(0x2788), 0x00000000 },
	{ _MMIO(0x278c), 0x0000f3ff },
	{ _MMIO(0x2790), 0x00000002 },
	{ _MMIO(0x2794), 0x0000fdff },
	{ _MMIO(0x2798), 0x00000000 },
	{ _MMIO(0x279c), 0x0000fe7f },
};

static const struct i915_oa_reg flex_eu_config_tdl_1[] = {
	{ _MMIO(0xE458), 0x00005004 },
	{ _MMIO(0xE558), 0x00010003 },
	{ _MMIO(0xE658), 0x00012011 },
	{ _MMIO(0xE758), 0x00015014 },
	{ _MMIO(0xE45c), 0x00051050 },
	{ _MMIO(0xE55c), 0x00053052 },
	{ _MMIO(0xE65c), 0x00055054 },
};

static const struct i915_oa_reg mux_config_tdl_1[] = {
	{ _MMIO(0x00009888), 0x141A0000 },
	{ _MMIO(0x00009888), 0x143A0000 },
	{ _MMIO(0x00009888), 0x145A0000 },
	{ _MMIO(0x00009888), 0x0C2D4000 },
	{ _MMIO(0x00009888), 0x0E2D5000 },
	{ _MMIO(0x00009888), 0x002D4000 },
	{ _MMIO(0x00009888), 0x022D5000 },
	{ _MMIO(0x00009888), 0x042D5000 },
	{ _MMIO(0x00009888), 0x062D1000 },
	{ _MMIO(0x00009888), 0x102E0150 },
	{ _MMIO(0x00009888), 0x0C2E5000 },
	{ _MMIO(0x00009888), 0x0E2E006A },
	{ _MMIO(0x00009888), 0x124C8000 },
	{ _MMIO(0x00009888), 0x144C8000 },
	{ _MMIO(0x00009888), 0x164C2000 },
	{ _MMIO(0x00009888), 0x044C8000 },
	{ _MMIO(0x00009888), 0x064C4000 },
	{ _MMIO(0x00009888), 0x0A4C4000 },
	{ _MMIO(0x00009888), 0x0C4E8000 },
	{ _MMIO(0x00009888), 0x0E4EA000 },
	{ _MMIO(0x00009888), 0x004E8000 },
	{ _MMIO(0x00009888), 0x024E2000 },
	{ _MMIO(0x00009888), 0x064E2000 },
	{ _MMIO(0x00009888), 0x1C0F0BC0 },
	{ _MMIO(0x00009888), 0x180F4000 },
	{ _MMIO(0x00009888), 0x1A0F0302 },
	{ _MMIO(0x00009888), 0x1E2C0003 },
	{ _MMIO(0x00009888), 0x1A2C00F0 },
	{ _MMIO(0x00009888), 0x021A3080 },
	{ _MMIO(0x00009888), 0x041A31E5 },
	{ _MMIO(0x00009888), 0x02148000 },
	{ _MMIO(0x00009888), 0x0414A000 },
	{ _MMIO(0x00009888), 0x1C150054 },
	{ _MMIO(0x00009888), 0x06168000 },
	{ _MMIO(0x00009888), 0x08168000 },
	{ _MMIO(0x00009888), 0x0A168000 },
	{ _MMIO(0x00009888), 0x0C3A3280 },
	{ _MMIO(0x00009888), 0x0E3A0063 },
	{ _MMIO(0x00009888), 0x063A0061 },
	{ _MMIO(0x00009888), 0x023A0000 },
	{ _MMIO(0x00009888), 0x0C348000 },
	{ _MMIO(0x00009888), 0x0E342000 },
	{ _MMIO(0x00009888), 0x06342000 },
	{ _MMIO(0x00009888), 0x1E350140 },
	{ _MMIO(0x00009888), 0x1C350100 },
	{ _MMIO(0x00009888), 0x18360028 },
	{ _MMIO(0x00009888), 0x0C368000 },
	{ _MMIO(0x00009888), 0x0E5A3080 },
	{ _MMIO(0x00009888), 0x005A3280 },
	{ _MMIO(0x00009888), 0x025A0063 },
	{ _MMIO(0x00009888), 0x0E548000 },
	{ _MMIO(0x00009888), 0x00548000 },
	{ _MMIO(0x00009888), 0x02542000 },
	{ _MMIO(0x00009888), 0x1E550400 },
	{ _MMIO(0x00009888), 0x1A552000 },
	{ _MMIO(0x00009888), 0x1C550001 },
	{ _MMIO(0x00009888), 0x18560080 },
	{ _MMIO(0x00009888), 0x02568000 },
	{ _MMIO(0x00009888), 0x04568000 },
	{ _MMIO(0x00009888), 0x1993A800 },
	{ _MMIO(0x00009888), 0x03938000 },
	{ _MMIO(0x00009888), 0x05938000 },
	{ _MMIO(0x00009888), 0x07938000 },
	{ _MMIO(0x00009888), 0x09938000 },
	{ _MMIO(0x00009888), 0x0B938000 },
	{ _MMIO(0x00009888), 0x0D938000 },
	{ _MMIO(0x00009888), 0x2D904000 },
	{ _MMIO(0x00009888), 0x2F904000 },
	{ _MMIO(0x00009888), 0x31904000 },
	{ _MMIO(0x00009888), 0x15904000 },
	{ _MMIO(0x00009888), 0x17904000 },
	{ _MMIO(0x00009888), 0x19904000 },
	{ _MMIO(0x00009888), 0x1B904000 },
	{ _MMIO(0x00009888), 0x1D904000 },
	{ _MMIO(0x00009888), 0x1F904000 },
	{ _MMIO(0x00009888), 0x59900000 },
	{ _MMIO(0x00009888), 0x4B900420 },
	{ _MMIO(0x00009888), 0x37900000 },
	{ _MMIO(0x00009888), 0x33900000 },
	{ _MMIO(0x00009888), 0x4D900000 },
	{ _MMIO(0x00009888), 0x53900000 },
	{ _MMIO(0x00009888), 0x43900000 },
	{ _MMIO(0x00009888), 0x45901084 },
	{ _MMIO(0x00009888), 0x55900000 },
	{ _MMIO(0x00009888), 0x47900001 },
};

static int select_tdl_1_config(struct drm_i915_private *dev_priv)
{
	dev_priv->perf.oa.mux_regs =
		mux_config_tdl_1;
	dev_priv->perf.oa.mux_regs_len =
		ARRAY_SIZE(mux_config_tdl_1);

	dev_priv->perf.oa.b_counter_regs =
		b_counter_config_tdl_1;
	dev_priv->perf.oa.b_counter_regs_len =
		ARRAY_SIZE(b_counter_config_tdl_1);

	dev_priv->perf.oa.flex_regs =
		flex_eu_config_tdl_1;
	dev_priv->perf.oa.flex_regs_len =
		ARRAY_SIZE(flex_eu_config_tdl_1);

	return 0;
}

static const struct i915_oa_reg b_counter_config_tdl_2[] = {
	{ _MMIO(0x2740), 0x00000000 },
	{ _MMIO(0x2744), 0x00800000 },
	{ _MMIO(0x2710), 0x00000000 },
	{ _MMIO(0x2714), 0x00800000 },
	{ _MMIO(0x2720), 0x00000000 },
	{ _MMIO(0x2724), 0x00800000 },
};

static const struct i915_oa_reg flex_eu_config_tdl_2[] = {
	{ _MMIO(0xE458), 0x00005004 },
	{ _MMIO(0xE558), 0x00010003 },
	{ _MMIO(0xE658), 0x00012011 },
	{ _MMIO(0xE758), 0x00015014 },
	{ _MMIO(0xE45c), 0x00051050 },
	{ _MMIO(0xE55c), 0x00053052 },
	{ _MMIO(0xE65c), 0x00055054 },
};

static const struct i915_oa_reg mux_config_tdl_2[] = {
	{ _MMIO(0x00009888), 0x141A026B },
	{ _MMIO(0x00009888), 0x143A0173 },
	{ _MMIO(0x00009888), 0x145A026B },
	{ _MMIO(0x00009888), 0x002D4000 },
	{ _MMIO(0x00009888), 0x022D5000 },
	{ _MMIO(0x00009888), 0x042D5000 },
	{ _MMIO(0x00009888), 0x062D1000 },
	{ _MMIO(0x00009888), 0x0C2E5000 },
	{ _MMIO(0x00009888), 0x0E2E0069 },
	{ _MMIO(0x00009888), 0x044C8000 },
	{ _MMIO(0x00009888), 0x064CC000 },
	{ _MMIO(0x00009888), 0x0A4C4000 },
	{ _MMIO(0x00009888), 0x004E8000 },
	{ _MMIO(0x00009888), 0x024EA000 },
	{ _MMIO(0x00009888), 0x064E2000 },
	{ _MMIO(0x00009888), 0x180F6000 },
	{ _MMIO(0x00009888), 0x1A0F030A },
	{ _MMIO(0x00009888), 0x1A2C03C0 },
	{ _MMIO(0x00009888), 0x041A37E7 },
	{ _MMIO(0x00009888), 0x021A0000 },
	{ _MMIO(0x00009888), 0x0414A000 },
	{ _MMIO(0x00009888), 0x1C150050 },
	{ _MMIO(0x00009888), 0x08168000 },
	{ _MMIO(0x00009888), 0x0A168000 },
	{ _MMIO(0x00009888), 0x003A3380 },
	{ _MMIO(0x00009888), 0x063A006F },
	{ _MMIO(0x00009888), 0x023A0000 },
	{ _MMIO(0x00009888), 0x00348000 },
	{ _MMIO(0x00009888), 0x06342000 },
	{ _MMIO(0x00009888), 0x1A352000 },
	{ _MMIO(0x00009888), 0x1C350100 },
	{ _MMIO(0x00009888), 0x02368000 },
	{ _MMIO(0x00009888), 0x0C368000 },
	{ _MMIO(0x00009888), 0x025A37E7 },
	{ _MMIO(0x00009888), 0x0254A000 },
	{ _MMIO(0x00009888), 0x1C550005 },
	{ _MMIO(0x00009888), 0x04568000 },
	{ _MMIO(0x00009888), 0x06568000 },
	{ _MMIO(0x00009888), 0x03938000 },
	{ _MMIO(0x00009888), 0x05938000 },
	{ _MMIO(0x00009888), 0x07938000 },
	{ _MMIO(0x00009888), 0x09938000 },
	{ _MMIO(0x00009888), 0x0B938000 },
	{ _MMIO(0x00009888), 0x0D938000 },
	{ _MMIO(0x00009888), 0x15904000 },
	{ _MMIO(0x00009888), 0x17904000 },
	{ _MMIO(0x00009888), 0x19904000 },
	{ _MMIO(0x00009888), 0x1B904000 },
	{ _MMIO(0x00009888), 0x1D904000 },
	{ _MMIO(0x00009888), 0x1F904000 },
	{ _MMIO(0x00009888), 0x37900000 },
	{ _MMIO(0x00009888), 0x53900000 },
	{ _MMIO(0x00009888), 0x43900020 },
	{ _MMIO(0x00009888), 0x45901080 },
	{ _MMIO(0x00009888), 0x55900000 },
	{ _MMIO(0x00009888), 0x47900001 },
	{ _MMIO(0x00009888), 0x33900000 },
};

static int select_tdl_2_config(struct drm_i915_private *dev_priv)
{
	dev_priv->perf.oa.mux_regs =
		mux_config_tdl_2;
	dev_priv->perf.oa.mux_regs_len =
		ARRAY_SIZE(mux_config_tdl_2);

	dev_priv->perf.oa.b_counter_regs =
		b_counter_config_tdl_2;
	dev_priv->perf.oa.b_counter_regs_len =
		ARRAY_SIZE(b_counter_config_tdl_2);

	dev_priv->perf.oa.flex_regs =
		flex_eu_config_tdl_2;
	dev_priv->perf.oa.flex_regs_len =
		ARRAY_SIZE(flex_eu_config_tdl_2);

	return 0;
}

int i915_oa_select_metric_set_bxt(struct drm_i915_private *dev_priv)
{
	dev_priv->perf.oa.mux_regs = NULL;
	dev_priv->perf.oa.mux_regs_len = 0;
	dev_priv->perf.oa.b_counter_regs = NULL;
	dev_priv->perf.oa.b_counter_regs_len = 0;
	dev_priv->perf.oa.flex_regs = NULL;
	dev_priv->perf.oa.flex_regs_len = 0;

	switch (dev_priv->perf.oa.metrics_set) {
	case METRIC_SET_ID_RENDER_BASIC:
		return select_render_basic_config(dev_priv);
	case METRIC_SET_ID_COMPUTE_BASIC:
		return select_compute_basic_config(dev_priv);
	case METRIC_SET_ID_RENDER_PIPE_PROFILE:
		return select_render_pipe_profile_config(dev_priv);
	case METRIC_SET_ID_MEMORY_READS:
		return select_memory_reads_config(dev_priv);
	case METRIC_SET_ID_MEMORY_WRITES:
		return select_memory_writes_config(dev_priv);
	case METRIC_SET_ID_COMPUTE_EXTENDED:
		return select_compute_extended_config(dev_priv);
	case METRIC_SET_ID_COMPUTE_L3_CACHE:
		return select_compute_l3_cache_config(dev_priv);
	case METRIC_SET_ID_HDC_AND_SF:
		return select_hdc_and_sf_config(dev_priv);
	case METRIC_SET_ID_L3_1:
		return select_l3_1_config(dev_priv);
	case METRIC_SET_ID_RASTERIZER_AND_PIXEL_BACKEND:
		return select_rasterizer_and_pixel_backend_config(dev_priv);
	case METRIC_SET_ID_SAMPLER:
		return select_sampler_config(dev_priv);
	case METRIC_SET_ID_TDL_1:
		return select_tdl_1_config(dev_priv);
	case METRIC_SET_ID_TDL_2:
		return select_tdl_2_config(dev_priv);
	default:
		return -ENODEV;
	}
}

static ssize_t
show_render_basic_id(struct device *kdev, struct device_attribute *attr, char *buf)
{
	return sprintf(buf, "%d\n", METRIC_SET_ID_RENDER_BASIC);
}

static struct device_attribute dev_attr_render_basic_id = {
	.attr = { .name = "id", .mode = S_IRUGO },
	.show = show_render_basic_id,
	.store = NULL,
};

static struct attribute *attrs_render_basic[] = {
	&dev_attr_render_basic_id.attr,
	NULL,
};

static struct attribute_group group_render_basic = {
	.name = "22b9519a-e9ba-4c41-8b54-f4f8ca14fa0a",
	.attrs =  attrs_render_basic,
};

static ssize_t
show_compute_basic_id(struct device *kdev, struct device_attribute *attr, char *buf)
{
	return sprintf(buf, "%d\n", METRIC_SET_ID_COMPUTE_BASIC);
}

static struct device_attribute dev_attr_compute_basic_id = {
	.attr = { .name = "id", .mode = S_IRUGO },
	.show = show_compute_basic_id,
	.store = NULL,
};

static struct attribute *attrs_compute_basic[] = {
	&dev_attr_compute_basic_id.attr,
	NULL,
};

static struct attribute_group group_compute_basic = {
	.name = "012d72cf-82a9-4d25-8ddf-74076fd30797",
	.attrs =  attrs_compute_basic,
};

static ssize_t
show_render_pipe_profile_id(struct device *kdev, struct device_attribute *attr, char *buf)
{
	return sprintf(buf, "%d\n", METRIC_SET_ID_RENDER_PIPE_PROFILE);
}

static struct device_attribute dev_attr_render_pipe_profile_id = {
	.attr = { .name = "id", .mode = S_IRUGO },
	.show = show_render_pipe_profile_id,
	.store = NULL,
};

static struct attribute *attrs_render_pipe_profile[] = {
	&dev_attr_render_pipe_profile_id.attr,
	NULL,
};

static struct attribute_group group_render_pipe_profile = {
	.name = "ce416533-e49e-4211-80af-ec513590a914",
	.attrs =  attrs_render_pipe_profile,
};

static ssize_t
show_memory_reads_id(struct device *kdev, struct device_attribute *attr, char *buf)
{
	return sprintf(buf, "%d\n", METRIC_SET_ID_MEMORY_READS);
}

static struct device_attribute dev_attr_memory_reads_id = {
	.attr = { .name = "id", .mode = S_IRUGO },
	.show = show_memory_reads_id,
	.store = NULL,
};

static struct attribute *attrs_memory_reads[] = {
	&dev_attr_memory_reads_id.attr,
	NULL,
};

static struct attribute_group group_memory_reads = {
	.name = "398e2452-18d7-42d0-b241-e4d0a9148ada",
	.attrs =  attrs_memory_reads,
};

static ssize_t
show_memory_writes_id(struct device *kdev, struct device_attribute *attr, char *buf)
{
	return sprintf(buf, "%d\n", METRIC_SET_ID_MEMORY_WRITES);
}

static struct device_attribute dev_attr_memory_writes_id = {
	.attr = { .name = "id", .mode = S_IRUGO },
	.show = show_memory_writes_id,
	.store = NULL,
};

static struct attribute *attrs_memory_writes[] = {
	&dev_attr_memory_writes_id.attr,
	NULL,
};

static struct attribute_group group_memory_writes = {
	.name = "d324a0d6-7269-4847-a5c2-6f71ddc7fed5",
	.attrs =  attrs_memory_writes,
};

static ssize_t
show_compute_extended_id(struct device *kdev, struct device_attribute *attr, char *buf)
{
	return sprintf(buf, "%d\n", METRIC_SET_ID_COMPUTE_EXTENDED);
}

static struct device_attribute dev_attr_compute_extended_id = {
	.attr = { .name = "id", .mode = S_IRUGO },
	.show = show_compute_extended_id,
	.store = NULL,
};

static struct attribute *attrs_compute_extended[] = {
	&dev_attr_compute_extended_id.attr,
	NULL,
};

static struct attribute_group group_compute_extended = {
	.name = "caf3596a-7bb1-4dec-b3b3-2a080d283b49",
	.attrs =  attrs_compute_extended,
};

static ssize_t
show_compute_l3_cache_id(struct device *kdev, struct device_attribute *attr, char *buf)
{
	return sprintf(buf, "%d\n", METRIC_SET_ID_COMPUTE_L3_CACHE);
}

static struct device_attribute dev_attr_compute_l3_cache_id = {
	.attr = { .name = "id", .mode = S_IRUGO },
	.show = show_compute_l3_cache_id,
	.store = NULL,
};

static struct attribute *attrs_compute_l3_cache[] = {
	&dev_attr_compute_l3_cache_id.attr,
	NULL,
};

static struct attribute_group group_compute_l3_cache = {
	.name = "49b956e2-d5b9-47e0-9d8a-cee5e8cec527",
	.attrs =  attrs_compute_l3_cache,
};

static ssize_t
show_hdc_and_sf_id(struct device *kdev, struct device_attribute *attr, char *buf)
{
	return sprintf(buf, "%d\n", METRIC_SET_ID_HDC_AND_SF);
}

static struct device_attribute dev_attr_hdc_and_sf_id = {
	.attr = { .name = "id", .mode = S_IRUGO },
	.show = show_hdc_and_sf_id,
	.store = NULL,
};

static struct attribute *attrs_hdc_and_sf[] = {
	&dev_attr_hdc_and_sf_id.attr,
	NULL,
};

static struct attribute_group group_hdc_and_sf = {
	.name = "f64ef50a-bdba-4b35-8f09-203c13d8ee5a",
	.attrs =  attrs_hdc_and_sf,
};

static ssize_t
show_l3_1_id(struct device *kdev, struct device_attribute *attr, char *buf)
{
	return sprintf(buf, "%d\n", METRIC_SET_ID_L3_1);
}

static struct device_attribute dev_attr_l3_1_id = {
	.attr = { .name = "id", .mode = S_IRUGO },
	.show = show_l3_1_id,
	.store = NULL,
};

static struct attribute *attrs_l3_1[] = {
	&dev_attr_l3_1_id.attr,
	NULL,
};

static struct attribute_group group_l3_1 = {
	.name = "00ad5a41-7eab-4f7a-9103-49d411c67219",
	.attrs =  attrs_l3_1,
};

static ssize_t
show_rasterizer_and_pixel_backend_id(struct device *kdev, struct device_attribute *attr, char *buf)
{
	return sprintf(buf, "%d\n", METRIC_SET_ID_RASTERIZER_AND_PIXEL_BACKEND);
}

static struct device_attribute dev_attr_rasterizer_and_pixel_backend_id = {
	.attr = { .name = "id", .mode = S_IRUGO },
	.show = show_rasterizer_and_pixel_backend_id,
	.store = NULL,
};

static struct attribute *attrs_rasterizer_and_pixel_backend[] = {
	&dev_attr_rasterizer_and_pixel_backend_id.attr,
	NULL,
};

static struct attribute_group group_rasterizer_and_pixel_backend = {
	.name = "46dc44ca-491c-4cc1-a951-e7b3e62bf02b",
	.attrs =  attrs_rasterizer_and_pixel_backend,
};

static ssize_t
show_sampler_id(struct device *kdev, struct device_attribute *attr, char *buf)
{
	return sprintf(buf, "%d\n", METRIC_SET_ID_SAMPLER);
}

static struct device_attribute dev_attr_sampler_id = {
	.attr = { .name = "id", .mode = S_IRUGO },
	.show = show_sampler_id,
	.store = NULL,
};

static struct attribute *attrs_sampler[] = {
	&dev_attr_sampler_id.attr,
	NULL,
};

static struct attribute_group group_sampler = {
	.name = "8364e2a8-af63-40af-b0d5-42969a255654",
	.attrs =  attrs_sampler,
};

static ssize_t
show_tdl_1_id(struct device *kdev, struct device_attribute *attr, char *buf)
{
	return sprintf(buf, "%d\n", METRIC_SET_ID_TDL_1);
}

static struct device_attribute dev_attr_tdl_1_id = {
	.attr = { .name = "id", .mode = S_IRUGO },
	.show = show_tdl_1_id,
	.store = NULL,
};

static struct attribute *attrs_tdl_1[] = {
	&dev_attr_tdl_1_id.attr,
	NULL,
};

static struct attribute_group group_tdl_1 = {
	.name = "175c8092-cb25-4d1e-8dc7-b4fdd39e2d92",
	.attrs =  attrs_tdl_1,
};

static ssize_t
show_tdl_2_id(struct device *kdev, struct device_attribute *attr, char *buf)
{
	return sprintf(buf, "%d\n", METRIC_SET_ID_TDL_2);
}

static struct device_attribute dev_attr_tdl_2_id = {
	.attr = { .name = "id", .mode = S_IRUGO },
	.show = show_tdl_2_id,
	.store = NULL,
};

static struct attribute *attrs_tdl_2[] = {
	&dev_attr_tdl_2_id.attr,
	NULL,
};

static struct attribute_group group_tdl_2 = {
	.name = "d260f03f-b34d-4b49-a44e-436819117332",
	.attrs =  attrs_tdl_2,
};

int
i915_perf_init_sysfs_bxt(struct drm_i915_private *dev_priv)
{
	int ret;

	ret = sysfs_create_group(dev_priv->perf.metrics_kobj, &group_render_basic);
	if (ret)
		goto error_render_basic;
	ret = sysfs_create_group(dev_priv->perf.metrics_kobj, &group_compute_basic);
	if (ret)
		goto error_compute_basic;
	ret = sysfs_create_group(dev_priv->perf.metrics_kobj, &group_render_pipe_profile);
	if (ret)
		goto error_render_pipe_profile;
	ret = sysfs_create_group(dev_priv->perf.metrics_kobj, &group_memory_reads);
	if (ret)
		goto error_memory_reads;
	ret = sysfs_create_group(dev_priv->perf.metrics_kobj, &group_memory_writes);
	if (ret)
		goto error_memory_writes;
	ret = sysfs_create_group(dev_priv->perf.metrics_kobj, &group_compute_extended);
	if (ret)
		goto error_compute_extended;
	ret = sysfs_create_group(dev_priv->perf.metrics_kobj, &group_compute_l3_cache);
	if (ret)
		goto error_compute_l3_cache;
	ret = sysfs_create_group(dev_priv->perf.metrics_kobj, &group_hdc_and_sf);
	if (ret)
		goto error_hdc_and_sf;
	ret = sysfs_create_group(dev_priv->perf.metrics_kobj, &group_l3_1);
	if (ret)
		goto error_l3_1;
	ret = sysfs_create_group(dev_priv->perf.metrics_kobj, &group_rasterizer_and_pixel_backend);
	if (ret)
		goto error_rasterizer_and_pixel_backend;
	ret = sysfs_create_group(dev_priv->perf.metrics_kobj, &group_sampler);
	if (ret)
		goto error_sampler;
	ret = sysfs_create_group(dev_priv->perf.metrics_kobj, &group_tdl_1);
	if (ret)
		goto error_tdl_1;
	ret = sysfs_create_group(dev_priv->perf.metrics_kobj, &group_tdl_2);
	if (ret)
		goto error_tdl_2;

	return 0;

error_tdl_2:
	sysfs_remove_group(dev_priv->perf.metrics_kobj, &group_tdl_1);
error_tdl_1:
	sysfs_remove_group(dev_priv->perf.metrics_kobj, &group_sampler);
error_sampler:
	sysfs_remove_group(dev_priv->perf.metrics_kobj, &group_rasterizer_and_pixel_backend);
error_rasterizer_and_pixel_backend:
	sysfs_remove_group(dev_priv->perf.metrics_kobj, &group_l3_1);
error_l3_1:
	sysfs_remove_group(dev_priv->perf.metrics_kobj, &group_hdc_and_sf);
error_hdc_and_sf:
	sysfs_remove_group(dev_priv->perf.metrics_kobj, &group_compute_l3_cache);
error_compute_l3_cache:
	sysfs_remove_group(dev_priv->perf.metrics_kobj, &group_compute_extended);
error_compute_extended:
	sysfs_remove_group(dev_priv->perf.metrics_kobj, &group_memory_writes);
error_memory_writes:
	sysfs_remove_group(dev_priv->perf.metrics_kobj, &group_memory_reads);
error_memory_reads:
	sysfs_remove_group(dev_priv->perf.metrics_kobj, &group_render_pipe_profile);
error_render_pipe_profile:
	sysfs_remove_group(dev_priv->perf.metrics_kobj, &group_compute_basic);
error_compute_basic:
	sysfs_remove_group(dev_priv->perf.metrics_kobj, &group_render_basic);
error_render_basic:
	return ret;
}

void
i915_perf_deinit_sysfs_bxt(struct drm_i915_private *dev_priv)
{
	sysfs_remove_group(dev_priv->perf.metrics_kobj, &group_render_basic);
	sysfs_remove_group(dev_priv->perf.metrics_kobj, &group_compute_basic);
	sysfs_remove_group(dev_priv->perf.metrics_kobj, &group_render_pipe_profile);
	sysfs_remove_group(dev_priv->perf.metrics_kobj, &group_memory_reads);
	sysfs_remove_group(dev_priv->perf.metrics_kobj, &group_memory_writes);
	sysfs_remove_group(dev_priv->perf.metrics_kobj, &group_compute_extended);
	sysfs_remove_group(dev_priv->perf.metrics_kobj, &group_compute_l3_cache);
	sysfs_remove_group(dev_priv->perf.metrics_kobj, &group_hdc_and_sf);
	sysfs_remove_group(dev_priv->perf.metrics_kobj, &group_l3_1);
	sysfs_remove_group(dev_priv->perf.metrics_kobj, &group_rasterizer_and_pixel_backend);
	sysfs_remove_group(dev_priv->perf.metrics_kobj, &group_sampler);
	sysfs_remove_group(dev_priv->perf.metrics_kobj, &group_tdl_1);
	sysfs_remove_group(dev_priv->perf.metrics_kobj, &group_tdl_2);
}
